// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module hls_snn_izikevich_snn_get_synaptic_conductances (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_stream0_TDATA,
        input_stream0_TVALID,
        input_stream0_TREADY,
        input_stream0_TKEEP,
        input_stream0_TSTRB,
        input_stream0_TUSER,
        input_stream0_TLAST,
        input_stream0_TID,
        input_stream0_TDEST,
        input_stream1_TDATA,
        input_stream1_TVALID,
        input_stream1_TREADY,
        input_stream1_TKEEP,
        input_stream1_TSTRB,
        input_stream1_TUSER,
        input_stream1_TLAST,
        input_stream1_TID,
        input_stream1_TDEST,
        input_stream2_TDATA,
        input_stream2_TVALID,
        input_stream2_TREADY,
        input_stream2_TKEEP,
        input_stream2_TSTRB,
        input_stream2_TUSER,
        input_stream2_TLAST,
        input_stream2_TID,
        input_stream2_TDEST,
        input_stream3_TDATA,
        input_stream3_TVALID,
        input_stream3_TREADY,
        input_stream3_TKEEP,
        input_stream3_TSTRB,
        input_stream3_TUSER,
        input_stream3_TLAST,
        input_stream3_TID,
        input_stream3_TDEST,
        neuron_type_mem_0,
        neuron_type_mem_1,
        synapse_s_mem_address0,
        synapse_s_mem_ce0,
        synapse_s_mem_q0,
        u_mem_address0,
        u_mem_ce0,
        u_mem_we0,
        u_mem_d0,
        u_mem_address1,
        u_mem_ce1,
        u_mem_q1,
        firings_mem_0_i,
        firings_mem_0_o,
        firings_mem_0_o_ap_vld,
        v_mem_address0,
        v_mem_ce0,
        v_mem_we0,
        v_mem_d0,
        v_mem_q0,
        grp_fu_537_p_din0,
        grp_fu_537_p_din1,
        grp_fu_537_p_opcode,
        grp_fu_537_p_dout0,
        grp_fu_537_p_ce,
        grp_fu_541_p_din0,
        grp_fu_541_p_din1,
        grp_fu_541_p_dout0,
        grp_fu_541_p_ce
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] input_stream0_TDATA;
input   input_stream0_TVALID;
output   input_stream0_TREADY;
input  [7:0] input_stream0_TKEEP;
input  [7:0] input_stream0_TSTRB;
input  [0:0] input_stream0_TUSER;
input  [0:0] input_stream0_TLAST;
input  [0:0] input_stream0_TID;
input  [0:0] input_stream0_TDEST;
input  [63:0] input_stream1_TDATA;
input   input_stream1_TVALID;
output   input_stream1_TREADY;
input  [7:0] input_stream1_TKEEP;
input  [7:0] input_stream1_TSTRB;
input  [0:0] input_stream1_TUSER;
input  [0:0] input_stream1_TLAST;
input  [0:0] input_stream1_TID;
input  [0:0] input_stream1_TDEST;
input  [63:0] input_stream2_TDATA;
input   input_stream2_TVALID;
output   input_stream2_TREADY;
input  [7:0] input_stream2_TKEEP;
input  [7:0] input_stream2_TSTRB;
input  [0:0] input_stream2_TUSER;
input  [0:0] input_stream2_TLAST;
input  [0:0] input_stream2_TID;
input  [0:0] input_stream2_TDEST;
input  [63:0] input_stream3_TDATA;
input   input_stream3_TVALID;
output   input_stream3_TREADY;
input  [7:0] input_stream3_TKEEP;
input  [7:0] input_stream3_TSTRB;
input  [0:0] input_stream3_TUSER;
input  [0:0] input_stream3_TLAST;
input  [0:0] input_stream3_TID;
input  [0:0] input_stream3_TDEST;
input  [5:0] neuron_type_mem_0;
input  [5:0] neuron_type_mem_1;
output  [3:0] synapse_s_mem_address0;
output   synapse_s_mem_ce0;
input  [31:0] synapse_s_mem_q0;
output  [3:0] u_mem_address0;
output   u_mem_ce0;
output   u_mem_we0;
output  [31:0] u_mem_d0;
output  [3:0] u_mem_address1;
output   u_mem_ce1;
input  [31:0] u_mem_q1;
input  [63:0] firings_mem_0_i;
output  [63:0] firings_mem_0_o;
output   firings_mem_0_o_ap_vld;
output  [3:0] v_mem_address0;
output   v_mem_ce0;
output   v_mem_we0;
output  [31:0] v_mem_d0;
input  [31:0] v_mem_q0;
output  [31:0] grp_fu_537_p_din0;
output  [31:0] grp_fu_537_p_din1;
output  [1:0] grp_fu_537_p_opcode;
input  [31:0] grp_fu_537_p_dout0;
output   grp_fu_537_p_ce;
output  [31:0] grp_fu_541_p_din0;
output  [31:0] grp_fu_541_p_din1;
input  [31:0] grp_fu_541_p_dout0;
output   grp_fu_541_p_ce;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg input_stream0_TREADY;
reg input_stream1_TREADY;
reg input_stream2_TREADY;
reg input_stream3_TREADY;
reg[3:0] synapse_s_mem_address0;
reg synapse_s_mem_ce0;
reg[63:0] firings_mem_0_o;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11;
reg   [31:0] snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9;
reg   [31:0] snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8;
reg   [31:0] snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7;
reg   [31:0] snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6;
reg   [31:0] snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10;
wire    grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_ap_start;
wire    grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_ap_done;
wire    grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_ap_idle;
wire    grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_ap_ready;
wire   [31:0] grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11;
wire    grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11_ap_vld;
wire   [3:0] grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_synapse_s_mem_address0;
wire    grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_synapse_s_mem_ce0;
wire   [31:0] grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9;
wire    grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9_ap_vld;
wire   [31:0] grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8;
wire    grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8_ap_vld;
wire   [31:0] grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7;
wire    grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7_ap_vld;
wire   [31:0] grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6;
wire    grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6_ap_vld;
wire   [31:0] grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10;
wire    grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10_ap_vld;
wire    grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_ap_start;
wire    grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_ap_done;
wire    grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_ap_idle;
wire    grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_ap_ready;
wire    grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_input_stream0_TREADY;
wire    grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_input_stream1_TREADY;
wire    grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_input_stream2_TREADY;
wire    grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_input_stream3_TREADY;
wire   [3:0] grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_u_mem_address0;
wire    grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_u_mem_ce0;
wire    grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_u_mem_we0;
wire   [31:0] grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_u_mem_d0;
wire   [3:0] grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_u_mem_address1;
wire    grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_u_mem_ce1;
wire   [63:0] grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_firings_mem_0_o;
wire    grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_firings_mem_0_o_ap_vld;
wire   [3:0] grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_v_mem_address0;
wire    grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_v_mem_ce0;
wire    grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_v_mem_we0;
wire   [31:0] grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_v_mem_d0;
wire   [31:0] grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11_o;
wire    grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11_o_ap_vld;
wire   [31:0] grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9_o;
wire    grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9_o_ap_vld;
wire   [31:0] grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8_o;
wire    grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8_o_ap_vld;
wire   [31:0] grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7_o;
wire    grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7_o_ap_vld;
wire   [31:0] grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6_o;
wire    grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6_o_ap_vld;
wire   [31:0] grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10_o;
wire    grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10_o_ap_vld;
wire   [3:0] grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_synapse_s_mem_address0;
wire    grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_synapse_s_mem_ce0;
wire   [31:0] grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_grp_fu_248_p_din0;
wire   [31:0] grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_grp_fu_248_p_din1;
wire   [1:0] grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_grp_fu_248_p_opcode;
wire    grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_grp_fu_248_p_ce;
wire   [31:0] grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_grp_fu_252_p_din0;
wire   [31:0] grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_grp_fu_252_p_din1;
wire    grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_grp_fu_252_p_ce;
reg    grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    grp_fu_248_ce;
reg    grp_fu_252_ce;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11 = 32'd0;
#0 snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9 = 32'd0;
#0 snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8 = 32'd0;
#0 snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7 = 32'd0;
#0 snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6 = 32'd0;
#0 snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10 = 32'd0;
#0 grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_ap_start_reg = 1'b0;
#0 grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_ap_start_reg = 1'b0;
end

hls_snn_izikevich_snn_get_synaptic_conductances_Pipeline_input_synapses_cache grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_ap_start),
    .ap_done(grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_ap_done),
    .ap_idle(grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_ap_idle),
    .ap_ready(grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_ap_ready),
    .snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11(grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11),
    .snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11_ap_vld(grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11_ap_vld),
    .synapse_s_mem_address0(grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_synapse_s_mem_address0),
    .synapse_s_mem_ce0(grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_synapse_s_mem_ce0),
    .synapse_s_mem_q0(synapse_s_mem_q0),
    .snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9(grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9),
    .snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9_ap_vld(grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9_ap_vld),
    .snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8(grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8),
    .snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8_ap_vld(grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8_ap_vld),
    .snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7(grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7),
    .snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7_ap_vld(grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7_ap_vld),
    .snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6(grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6),
    .snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6_ap_vld(grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6_ap_vld),
    .snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10(grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10),
    .snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10_ap_vld(grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10_ap_vld)
);

hls_snn_izikevich_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1 grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_ap_start),
    .ap_done(grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_ap_done),
    .ap_idle(grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_ap_idle),
    .ap_ready(grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_ap_ready),
    .neuron_type_mem_0_load(neuron_type_mem_0),
    .neuron_type_mem_1_load(neuron_type_mem_1),
    .input_stream0_TDATA(input_stream0_TDATA),
    .input_stream0_TVALID(input_stream0_TVALID),
    .input_stream0_TREADY(grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_input_stream0_TREADY),
    .input_stream0_TKEEP(input_stream0_TKEEP),
    .input_stream0_TSTRB(input_stream0_TSTRB),
    .input_stream0_TUSER(input_stream0_TUSER),
    .input_stream0_TLAST(input_stream0_TLAST),
    .input_stream0_TID(input_stream0_TID),
    .input_stream0_TDEST(input_stream0_TDEST),
    .input_stream1_TDATA(input_stream1_TDATA),
    .input_stream1_TVALID(input_stream1_TVALID),
    .input_stream1_TREADY(grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_input_stream1_TREADY),
    .input_stream1_TKEEP(input_stream1_TKEEP),
    .input_stream1_TSTRB(input_stream1_TSTRB),
    .input_stream1_TUSER(input_stream1_TUSER),
    .input_stream1_TLAST(input_stream1_TLAST),
    .input_stream1_TID(input_stream1_TID),
    .input_stream1_TDEST(input_stream1_TDEST),
    .input_stream2_TDATA(input_stream2_TDATA),
    .input_stream2_TVALID(input_stream2_TVALID),
    .input_stream2_TREADY(grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_input_stream2_TREADY),
    .input_stream2_TKEEP(input_stream2_TKEEP),
    .input_stream2_TSTRB(input_stream2_TSTRB),
    .input_stream2_TUSER(input_stream2_TUSER),
    .input_stream2_TLAST(input_stream2_TLAST),
    .input_stream2_TID(input_stream2_TID),
    .input_stream2_TDEST(input_stream2_TDEST),
    .input_stream3_TDATA(input_stream3_TDATA),
    .input_stream3_TVALID(input_stream3_TVALID),
    .input_stream3_TREADY(grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_input_stream3_TREADY),
    .input_stream3_TKEEP(input_stream3_TKEEP),
    .input_stream3_TSTRB(input_stream3_TSTRB),
    .input_stream3_TUSER(input_stream3_TUSER),
    .input_stream3_TLAST(input_stream3_TLAST),
    .input_stream3_TID(input_stream3_TID),
    .input_stream3_TDEST(input_stream3_TDEST),
    .u_mem_address0(grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_u_mem_address0),
    .u_mem_ce0(grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_u_mem_ce0),
    .u_mem_we0(grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_u_mem_we0),
    .u_mem_d0(grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_u_mem_d0),
    .u_mem_address1(grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_u_mem_address1),
    .u_mem_ce1(grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_u_mem_ce1),
    .u_mem_q1(u_mem_q1),
    .firings_mem_0_i(firings_mem_0_i),
    .firings_mem_0_o(grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_firings_mem_0_o),
    .firings_mem_0_o_ap_vld(grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_firings_mem_0_o_ap_vld),
    .v_mem_address0(grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_v_mem_address0),
    .v_mem_ce0(grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_v_mem_ce0),
    .v_mem_we0(grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_v_mem_we0),
    .v_mem_d0(grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_v_mem_d0),
    .v_mem_q0(v_mem_q0),
    .snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11_i(snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11),
    .snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11_o(grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11_o),
    .snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11_o_ap_vld(grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11_o_ap_vld),
    .snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9_i(snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9),
    .snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9_o(grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9_o),
    .snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9_o_ap_vld(grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9_o_ap_vld),
    .snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8_i(snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8),
    .snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8_o(grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8_o),
    .snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8_o_ap_vld(grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8_o_ap_vld),
    .snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7_i(snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7),
    .snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7_o(grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7_o),
    .snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7_o_ap_vld(grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7_o_ap_vld),
    .snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6_i(snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6),
    .snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6_o(grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6_o),
    .snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6_o_ap_vld(grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6_o_ap_vld),
    .snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10_i(snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10),
    .snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10_o(grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10_o),
    .snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10_o_ap_vld(grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10_o_ap_vld),
    .synapse_s_mem_address0(grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_synapse_s_mem_address0),
    .synapse_s_mem_ce0(grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_synapse_s_mem_ce0),
    .synapse_s_mem_q0(synapse_s_mem_q0),
    .grp_fu_248_p_din0(grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_grp_fu_248_p_din0),
    .grp_fu_248_p_din1(grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_grp_fu_248_p_din1),
    .grp_fu_248_p_opcode(grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_grp_fu_248_p_opcode),
    .grp_fu_248_p_dout0(grp_fu_537_p_dout0),
    .grp_fu_248_p_ce(grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_grp_fu_248_p_ce),
    .grp_fu_252_p_din0(grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_grp_fu_252_p_din0),
    .grp_fu_252_p_din1(grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_grp_fu_252_p_din1),
    .grp_fu_252_p_dout0(grp_fu_541_p_dout0),
    .grp_fu_252_p_ce(grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_grp_fu_252_p_ce)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_ap_start_reg <= 1'b1;
        end else if ((grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_ap_ready == 1'b1)) begin
            grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_ap_start_reg <= 1'b1;
        end else if ((grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_ap_ready == 1'b1)) begin
            grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10_o_ap_vld == 1'b1))) begin
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10 <= grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10_o;
    end else if (((1'b1 == ap_CS_fsm_state2) & (grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10_ap_vld == 1'b1))) begin
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10 <= grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11_o_ap_vld == 1'b1))) begin
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11 <= grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11_o;
    end else if (((1'b1 == ap_CS_fsm_state2) & (grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11_ap_vld == 1'b1))) begin
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11 <= grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6_o_ap_vld == 1'b1))) begin
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6 <= grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6_o;
    end else if (((1'b1 == ap_CS_fsm_state2) & (grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6_ap_vld == 1'b1))) begin
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6 <= grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7_o_ap_vld == 1'b1))) begin
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7 <= grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7_o;
    end else if (((1'b1 == ap_CS_fsm_state2) & (grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7_ap_vld == 1'b1))) begin
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7 <= grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8_o_ap_vld == 1'b1))) begin
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8 <= grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8_o;
    end else if (((1'b1 == ap_CS_fsm_state2) & (grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8_ap_vld == 1'b1))) begin
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8 <= grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9_o_ap_vld == 1'b1))) begin
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9 <= grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9_o;
    end else if (((1'b1 == ap_CS_fsm_state2) & (grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9_ap_vld == 1'b1))) begin
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9 <= grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state4) & (grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_ap_done == 1'b1)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_ap_done == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_firings_mem_0_o_ap_vld == 1'b1))) begin
        firings_mem_0_o = grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_firings_mem_0_o;
    end else begin
        firings_mem_0_o = firings_mem_0_i;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_248_ce = grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_grp_fu_248_p_ce;
    end else begin
        grp_fu_248_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_252_ce = grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_grp_fu_252_p_ce;
    end else begin
        grp_fu_252_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_stream0_TREADY = grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_input_stream0_TREADY;
    end else begin
        input_stream0_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_stream1_TREADY = grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_input_stream1_TREADY;
    end else begin
        input_stream1_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_stream2_TREADY = grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_input_stream2_TREADY;
    end else begin
        input_stream2_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_stream3_TREADY = grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_input_stream3_TREADY;
    end else begin
        input_stream3_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        synapse_s_mem_address0 = grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_synapse_s_mem_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        synapse_s_mem_address0 = grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_synapse_s_mem_address0;
    end else begin
        synapse_s_mem_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        synapse_s_mem_ce0 = grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_synapse_s_mem_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        synapse_s_mem_ce0 = grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_synapse_s_mem_ce0;
    end else begin
        synapse_s_mem_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign firings_mem_0_o_ap_vld = grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_firings_mem_0_o_ap_vld;

assign grp_fu_537_p_ce = grp_fu_248_ce;

assign grp_fu_537_p_din0 = grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_grp_fu_248_p_din0;

assign grp_fu_537_p_din1 = grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_grp_fu_248_p_din1;

assign grp_fu_537_p_opcode = grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_grp_fu_248_p_opcode;

assign grp_fu_541_p_ce = grp_fu_252_ce;

assign grp_fu_541_p_din0 = grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_grp_fu_252_p_din0;

assign grp_fu_541_p_din1 = grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_grp_fu_252_p_din1;

assign grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_ap_start = grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_120_ap_start_reg;

assign grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_ap_start = grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_ap_start_reg;

assign u_mem_address0 = grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_u_mem_address0;

assign u_mem_address1 = grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_u_mem_address1;

assign u_mem_ce0 = grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_u_mem_ce0;

assign u_mem_ce1 = grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_u_mem_ce1;

assign u_mem_d0 = grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_u_mem_d0;

assign u_mem_we0 = grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_u_mem_we0;

assign v_mem_address0 = grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_v_mem_address0;

assign v_mem_ce0 = grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_v_mem_ce0;

assign v_mem_d0 = grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_v_mem_d0;

assign v_mem_we0 = grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_138_v_mem_we0;

endmodule //hls_snn_izikevich_snn_get_synaptic_conductances
