// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="hls_snn_izikevich_hls_snn_izikevich,hls_ip_2023_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=40.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=28.252000,HLS_SYN_LAT=204,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=6471,HLS_SYN_LUT=7144,HLS_VERSION=2023_1}" *)

module hls_snn_izikevich (
        ap_clk,
        ap_rst_n,
        input_stream0_TDATA,
        input_stream0_TVALID,
        input_stream0_TREADY,
        input_stream0_TKEEP,
        input_stream0_TSTRB,
        input_stream0_TUSER,
        input_stream0_TLAST,
        input_stream0_TID,
        input_stream0_TDEST,
        input_stream1_TDATA,
        input_stream1_TVALID,
        input_stream1_TREADY,
        input_stream1_TKEEP,
        input_stream1_TSTRB,
        input_stream1_TUSER,
        input_stream1_TLAST,
        input_stream1_TID,
        input_stream1_TDEST,
        input_stream2_TDATA,
        input_stream2_TVALID,
        input_stream2_TREADY,
        input_stream2_TKEEP,
        input_stream2_TSTRB,
        input_stream2_TUSER,
        input_stream2_TLAST,
        input_stream2_TID,
        input_stream2_TDEST,
        input_stream3_TDATA,
        input_stream3_TVALID,
        input_stream3_TREADY,
        input_stream3_TKEEP,
        input_stream3_TSTRB,
        input_stream3_TUSER,
        input_stream3_TLAST,
        input_stream3_TID,
        input_stream3_TDEST,
        output_stream_TDATA,
        output_stream_TVALID,
        output_stream_TREADY,
        output_stream_TKEEP,
        output_stream_TSTRB,
        output_stream_TUSER,
        output_stream_TLAST,
        output_stream_TID,
        output_stream_TDEST,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 14'd1;
parameter    ap_ST_fsm_state2 = 14'd2;
parameter    ap_ST_fsm_state3 = 14'd4;
parameter    ap_ST_fsm_state4 = 14'd8;
parameter    ap_ST_fsm_state5 = 14'd16;
parameter    ap_ST_fsm_state6 = 14'd32;
parameter    ap_ST_fsm_state7 = 14'd64;
parameter    ap_ST_fsm_state8 = 14'd128;
parameter    ap_ST_fsm_state9 = 14'd256;
parameter    ap_ST_fsm_state10 = 14'd512;
parameter    ap_ST_fsm_state11 = 14'd1024;
parameter    ap_ST_fsm_state12 = 14'd2048;
parameter    ap_ST_fsm_state13 = 14'd4096;
parameter    ap_ST_fsm_state14 = 14'd8192;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [63:0] input_stream0_TDATA;
input   input_stream0_TVALID;
output   input_stream0_TREADY;
input  [7:0] input_stream0_TKEEP;
input  [7:0] input_stream0_TSTRB;
input  [0:0] input_stream0_TUSER;
input  [0:0] input_stream0_TLAST;
input  [0:0] input_stream0_TID;
input  [0:0] input_stream0_TDEST;
input  [63:0] input_stream1_TDATA;
input   input_stream1_TVALID;
output   input_stream1_TREADY;
input  [7:0] input_stream1_TKEEP;
input  [7:0] input_stream1_TSTRB;
input  [0:0] input_stream1_TUSER;
input  [0:0] input_stream1_TLAST;
input  [0:0] input_stream1_TID;
input  [0:0] input_stream1_TDEST;
input  [63:0] input_stream2_TDATA;
input   input_stream2_TVALID;
output   input_stream2_TREADY;
input  [7:0] input_stream2_TKEEP;
input  [7:0] input_stream2_TSTRB;
input  [0:0] input_stream2_TUSER;
input  [0:0] input_stream2_TLAST;
input  [0:0] input_stream2_TID;
input  [0:0] input_stream2_TDEST;
input  [63:0] input_stream3_TDATA;
input   input_stream3_TVALID;
output   input_stream3_TREADY;
input  [7:0] input_stream3_TKEEP;
input  [7:0] input_stream3_TSTRB;
input  [0:0] input_stream3_TUSER;
input  [0:0] input_stream3_TLAST;
input  [0:0] input_stream3_TID;
input  [0:0] input_stream3_TDEST;
output  [63:0] output_stream_TDATA;
output   output_stream_TVALID;
input   output_stream_TREADY;
output  [7:0] output_stream_TKEEP;
output  [7:0] output_stream_TSTRB;
output  [0:0] output_stream_TUSER;
output  [0:0] output_stream_TLAST;
output  [0:0] output_stream_TID;
output  [0:0] output_stream_TDEST;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [13:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [0:0] state;
wire   [31:0] p_input;
reg   [0:0] output_indexes_address0;
reg    output_indexes_ce0;
wire   [31:0] output_indexes_q0;
reg   [5:0] neuron_type_mem_0;
reg   [5:0] neuron_type_mem_1;
reg   [3:0] output_indexes_mem_0;
reg   [3:0] output_indexes_mem_1;
reg   [3:0] v_mem_address0;
reg    v_mem_ce0;
reg    v_mem_we0;
reg   [31:0] v_mem_d0;
wire   [31:0] v_mem_q0;
wire   [3:0] v_mem_address1;
reg    v_mem_ce1;
wire   [31:0] v_mem_q1;
reg   [3:0] u_mem_address0;
reg    u_mem_ce0;
reg    u_mem_we0;
reg   [31:0] u_mem_d0;
reg    u_mem_ce1;
wire   [31:0] u_mem_q1;
reg   [2:0] p_mem_address0;
reg    p_mem_ce0;
reg    p_mem_we0;
wire   [0:0] p_mem_q0;
reg   [3:0] synapse_s_mem_address0;
reg    synapse_s_mem_ce0;
reg    synapse_s_mem_we0;
wire   [31:0] synapse_s_mem_q0;
reg    synapse_s_mem_ce1;
wire   [31:0] synapse_s_mem_q1;
reg   [63:0] firings_mem_0;
reg    output_stream_TDATA_blk_n;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
wire   [0:0] state_read_read_fu_204_p2;
reg   [0:0] state_read_reg_500;
reg   [31:0] p_input_read_reg_504;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state11;
wire   [63:0] c_fu_486_p3;
wire    grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_15_2_fu_296_ap_start;
wire    grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_15_2_fu_296_ap_done;
wire    grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_15_2_fu_296_ap_idle;
wire    grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_15_2_fu_296_ap_ready;
wire    grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_15_2_fu_296_input_stream0_TREADY;
wire   [5:0] grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_15_2_fu_296_neuron_type_mem_0_o;
wire    grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_15_2_fu_296_neuron_type_mem_0_o_ap_vld;
wire   [5:0] grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_15_2_fu_296_neuron_type_mem_1_o;
wire    grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_15_2_fu_296_neuron_type_mem_1_o_ap_vld;
wire    grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_43_2_fu_318_ap_start;
wire    grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_43_2_fu_318_ap_done;
wire    grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_43_2_fu_318_ap_idle;
wire    grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_43_2_fu_318_ap_ready;
wire   [2:0] grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_43_2_fu_318_p_mem_address0;
wire    grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_43_2_fu_318_p_mem_ce0;
wire    grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_43_2_fu_318_p_mem_we0;
wire   [0:0] grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_43_2_fu_318_p_mem_d0;
wire    grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_47_2_fu_326_ap_start;
wire    grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_47_2_fu_326_ap_done;
wire    grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_47_2_fu_326_ap_idle;
wire    grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_47_2_fu_326_ap_ready;
wire   [3:0] grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_47_2_fu_326_v_mem_address0;
wire    grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_47_2_fu_326_v_mem_ce0;
wire    grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_47_2_fu_326_v_mem_we0;
wire   [31:0] grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_47_2_fu_326_v_mem_d0;
wire   [3:0] grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_47_2_fu_326_u_mem_address0;
wire    grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_47_2_fu_326_u_mem_ce0;
wire    grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_47_2_fu_326_u_mem_we0;
wire   [31:0] grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_47_2_fu_326_u_mem_d0;
wire    grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_ap_start;
wire    grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_ap_done;
wire    grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_ap_idle;
wire    grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_ap_ready;
wire   [3:0] grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_synapse_s_mem_address0;
wire    grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_synapse_s_mem_ce0;
wire    grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_synapse_s_mem_we0;
wire   [31:0] grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_synapse_s_mem_d0;
wire   [3:0] grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_synapse_s_mem_address1;
wire    grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_synapse_s_mem_ce1;
wire   [3:0] grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_v_mem_address0;
wire    grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_v_mem_ce0;
wire   [2:0] grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_p_mem_address0;
wire    grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_p_mem_ce0;
wire   [31:0] grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_grp_fu_537_p_din0;
wire   [31:0] grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_grp_fu_537_p_din1;
wire   [0:0] grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_grp_fu_537_p_opcode;
wire    grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_grp_fu_537_p_ce;
wire   [31:0] grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_grp_fu_541_p_din0;
wire   [31:0] grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_grp_fu_541_p_din1;
wire    grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_grp_fu_541_p_ce;
wire    grp_snn_get_synaptic_conductances_fu_344_ap_start;
wire    grp_snn_get_synaptic_conductances_fu_344_ap_done;
wire    grp_snn_get_synaptic_conductances_fu_344_ap_idle;
wire    grp_snn_get_synaptic_conductances_fu_344_ap_ready;
wire    grp_snn_get_synaptic_conductances_fu_344_input_stream0_TREADY;
wire    grp_snn_get_synaptic_conductances_fu_344_input_stream1_TREADY;
wire    grp_snn_get_synaptic_conductances_fu_344_input_stream2_TREADY;
wire    grp_snn_get_synaptic_conductances_fu_344_input_stream3_TREADY;
wire   [3:0] grp_snn_get_synaptic_conductances_fu_344_synapse_s_mem_address0;
wire    grp_snn_get_synaptic_conductances_fu_344_synapse_s_mem_ce0;
wire   [3:0] grp_snn_get_synaptic_conductances_fu_344_u_mem_address0;
wire    grp_snn_get_synaptic_conductances_fu_344_u_mem_ce0;
wire    grp_snn_get_synaptic_conductances_fu_344_u_mem_we0;
wire   [31:0] grp_snn_get_synaptic_conductances_fu_344_u_mem_d0;
wire   [3:0] grp_snn_get_synaptic_conductances_fu_344_u_mem_address1;
wire    grp_snn_get_synaptic_conductances_fu_344_u_mem_ce1;
wire   [63:0] grp_snn_get_synaptic_conductances_fu_344_firings_mem_0_o;
wire    grp_snn_get_synaptic_conductances_fu_344_firings_mem_0_o_ap_vld;
wire   [3:0] grp_snn_get_synaptic_conductances_fu_344_v_mem_address0;
wire    grp_snn_get_synaptic_conductances_fu_344_v_mem_ce0;
wire    grp_snn_get_synaptic_conductances_fu_344_v_mem_we0;
wire   [31:0] grp_snn_get_synaptic_conductances_fu_344_v_mem_d0;
wire   [31:0] grp_snn_get_synaptic_conductances_fu_344_grp_fu_537_p_din0;
wire   [31:0] grp_snn_get_synaptic_conductances_fu_344_grp_fu_537_p_din1;
wire   [1:0] grp_snn_get_synaptic_conductances_fu_344_grp_fu_537_p_opcode;
wire    grp_snn_get_synaptic_conductances_fu_344_grp_fu_537_p_ce;
wire   [31:0] grp_snn_get_synaptic_conductances_fu_344_grp_fu_541_p_din0;
wire   [31:0] grp_snn_get_synaptic_conductances_fu_344_grp_fu_541_p_din1;
wire    grp_snn_get_synaptic_conductances_fu_344_grp_fu_541_p_ce;
reg    grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_15_2_fu_296_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_43_2_fu_318_ap_start_reg;
wire    ap_CS_fsm_state6;
reg    grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_47_2_fu_326_ap_start_reg;
reg    grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_ap_start_reg;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
reg    grp_snn_get_synaptic_conductances_fu_344_ap_start_reg;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
reg    ap_block_state10_on_subcall_done;
wire   [63:0] zext_ln74_fu_464_p1;
wire   [63:0] zext_ln74_1_fu_473_p1;
wire   [3:0] trunc_ln43_fu_440_p1;
wire   [3:0] trunc_ln43_1_fu_450_p1;
wire    ap_CS_fsm_state5;
wire   [31:0] bitcast_ln110_fu_482_p1;
wire   [31:0] bitcast_ln109_fu_478_p1;
wire   [31:0] grp_fu_537_p2;
reg   [31:0] grp_fu_537_p0;
reg   [31:0] grp_fu_537_p1;
reg   [1:0] grp_fu_537_opcode;
reg    grp_fu_537_ce;
wire   [31:0] grp_fu_541_p2;
reg   [31:0] grp_fu_541_p0;
reg   [31:0] grp_fu_541_p1;
reg    grp_fu_541_ce;
wire    regslice_both_output_stream_V_data_V_U_apdone_blk;
reg    ap_block_state14;
reg   [13:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
reg    ap_ST_fsm_state14_blk;
wire    regslice_both_input_stream0_V_data_V_U_apdone_blk;
wire   [63:0] input_stream0_TDATA_int_regslice;
wire    input_stream0_TVALID_int_regslice;
reg    input_stream0_TREADY_int_regslice;
wire    regslice_both_input_stream0_V_data_V_U_ack_in;
wire    regslice_both_input_stream0_V_keep_V_U_apdone_blk;
wire   [7:0] input_stream0_TKEEP_int_regslice;
wire    regslice_both_input_stream0_V_keep_V_U_vld_out;
wire    regslice_both_input_stream0_V_keep_V_U_ack_in;
wire    regslice_both_input_stream0_V_strb_V_U_apdone_blk;
wire   [7:0] input_stream0_TSTRB_int_regslice;
wire    regslice_both_input_stream0_V_strb_V_U_vld_out;
wire    regslice_both_input_stream0_V_strb_V_U_ack_in;
wire    regslice_both_input_stream0_V_user_V_U_apdone_blk;
wire   [0:0] input_stream0_TUSER_int_regslice;
wire    regslice_both_input_stream0_V_user_V_U_vld_out;
wire    regslice_both_input_stream0_V_user_V_U_ack_in;
wire    regslice_both_input_stream0_V_last_V_U_apdone_blk;
wire   [0:0] input_stream0_TLAST_int_regslice;
wire    regslice_both_input_stream0_V_last_V_U_vld_out;
wire    regslice_both_input_stream0_V_last_V_U_ack_in;
wire    regslice_both_input_stream0_V_id_V_U_apdone_blk;
wire   [0:0] input_stream0_TID_int_regslice;
wire    regslice_both_input_stream0_V_id_V_U_vld_out;
wire    regslice_both_input_stream0_V_id_V_U_ack_in;
wire    regslice_both_input_stream0_V_dest_V_U_apdone_blk;
wire   [0:0] input_stream0_TDEST_int_regslice;
wire    regslice_both_input_stream0_V_dest_V_U_vld_out;
wire    regslice_both_input_stream0_V_dest_V_U_ack_in;
wire    regslice_both_input_stream1_V_data_V_U_apdone_blk;
wire   [63:0] input_stream1_TDATA_int_regslice;
wire    input_stream1_TVALID_int_regslice;
reg    input_stream1_TREADY_int_regslice;
wire    regslice_both_input_stream1_V_data_V_U_ack_in;
wire    regslice_both_input_stream1_V_keep_V_U_apdone_blk;
wire   [7:0] input_stream1_TKEEP_int_regslice;
wire    regslice_both_input_stream1_V_keep_V_U_vld_out;
wire    regslice_both_input_stream1_V_keep_V_U_ack_in;
wire    regslice_both_input_stream1_V_strb_V_U_apdone_blk;
wire   [7:0] input_stream1_TSTRB_int_regslice;
wire    regslice_both_input_stream1_V_strb_V_U_vld_out;
wire    regslice_both_input_stream1_V_strb_V_U_ack_in;
wire    regslice_both_input_stream1_V_user_V_U_apdone_blk;
wire   [0:0] input_stream1_TUSER_int_regslice;
wire    regslice_both_input_stream1_V_user_V_U_vld_out;
wire    regslice_both_input_stream1_V_user_V_U_ack_in;
wire    regslice_both_input_stream1_V_last_V_U_apdone_blk;
wire   [0:0] input_stream1_TLAST_int_regslice;
wire    regslice_both_input_stream1_V_last_V_U_vld_out;
wire    regslice_both_input_stream1_V_last_V_U_ack_in;
wire    regslice_both_input_stream1_V_id_V_U_apdone_blk;
wire   [0:0] input_stream1_TID_int_regslice;
wire    regslice_both_input_stream1_V_id_V_U_vld_out;
wire    regslice_both_input_stream1_V_id_V_U_ack_in;
wire    regslice_both_input_stream1_V_dest_V_U_apdone_blk;
wire   [0:0] input_stream1_TDEST_int_regslice;
wire    regslice_both_input_stream1_V_dest_V_U_vld_out;
wire    regslice_both_input_stream1_V_dest_V_U_ack_in;
wire    regslice_both_input_stream2_V_data_V_U_apdone_blk;
wire   [63:0] input_stream2_TDATA_int_regslice;
wire    input_stream2_TVALID_int_regslice;
reg    input_stream2_TREADY_int_regslice;
wire    regslice_both_input_stream2_V_data_V_U_ack_in;
wire    regslice_both_input_stream2_V_keep_V_U_apdone_blk;
wire   [7:0] input_stream2_TKEEP_int_regslice;
wire    regslice_both_input_stream2_V_keep_V_U_vld_out;
wire    regslice_both_input_stream2_V_keep_V_U_ack_in;
wire    regslice_both_input_stream2_V_strb_V_U_apdone_blk;
wire   [7:0] input_stream2_TSTRB_int_regslice;
wire    regslice_both_input_stream2_V_strb_V_U_vld_out;
wire    regslice_both_input_stream2_V_strb_V_U_ack_in;
wire    regslice_both_input_stream2_V_user_V_U_apdone_blk;
wire   [0:0] input_stream2_TUSER_int_regslice;
wire    regslice_both_input_stream2_V_user_V_U_vld_out;
wire    regslice_both_input_stream2_V_user_V_U_ack_in;
wire    regslice_both_input_stream2_V_last_V_U_apdone_blk;
wire   [0:0] input_stream2_TLAST_int_regslice;
wire    regslice_both_input_stream2_V_last_V_U_vld_out;
wire    regslice_both_input_stream2_V_last_V_U_ack_in;
wire    regslice_both_input_stream2_V_id_V_U_apdone_blk;
wire   [0:0] input_stream2_TID_int_regslice;
wire    regslice_both_input_stream2_V_id_V_U_vld_out;
wire    regslice_both_input_stream2_V_id_V_U_ack_in;
wire    regslice_both_input_stream2_V_dest_V_U_apdone_blk;
wire   [0:0] input_stream2_TDEST_int_regslice;
wire    regslice_both_input_stream2_V_dest_V_U_vld_out;
wire    regslice_both_input_stream2_V_dest_V_U_ack_in;
wire    regslice_both_input_stream3_V_data_V_U_apdone_blk;
wire   [63:0] input_stream3_TDATA_int_regslice;
wire    input_stream3_TVALID_int_regslice;
reg    input_stream3_TREADY_int_regslice;
wire    regslice_both_input_stream3_V_data_V_U_ack_in;
wire    regslice_both_input_stream3_V_keep_V_U_apdone_blk;
wire   [7:0] input_stream3_TKEEP_int_regslice;
wire    regslice_both_input_stream3_V_keep_V_U_vld_out;
wire    regslice_both_input_stream3_V_keep_V_U_ack_in;
wire    regslice_both_input_stream3_V_strb_V_U_apdone_blk;
wire   [7:0] input_stream3_TSTRB_int_regslice;
wire    regslice_both_input_stream3_V_strb_V_U_vld_out;
wire    regslice_both_input_stream3_V_strb_V_U_ack_in;
wire    regslice_both_input_stream3_V_user_V_U_apdone_blk;
wire   [0:0] input_stream3_TUSER_int_regslice;
wire    regslice_both_input_stream3_V_user_V_U_vld_out;
wire    regslice_both_input_stream3_V_user_V_U_ack_in;
wire    regslice_both_input_stream3_V_last_V_U_apdone_blk;
wire   [0:0] input_stream3_TLAST_int_regslice;
wire    regslice_both_input_stream3_V_last_V_U_vld_out;
wire    regslice_both_input_stream3_V_last_V_U_ack_in;
wire    regslice_both_input_stream3_V_id_V_U_apdone_blk;
wire   [0:0] input_stream3_TID_int_regslice;
wire    regslice_both_input_stream3_V_id_V_U_vld_out;
wire    regslice_both_input_stream3_V_id_V_U_ack_in;
wire    regslice_both_input_stream3_V_dest_V_U_apdone_blk;
wire   [0:0] input_stream3_TDEST_int_regslice;
wire    regslice_both_input_stream3_V_dest_V_U_vld_out;
wire    regslice_both_input_stream3_V_dest_V_U_ack_in;
reg   [63:0] output_stream_TDATA_int_regslice;
reg    output_stream_TVALID_int_regslice;
wire    output_stream_TREADY_int_regslice;
wire    regslice_both_output_stream_V_data_V_U_vld_out;
wire    regslice_both_output_stream_V_keep_V_U_apdone_blk;
wire    regslice_both_output_stream_V_keep_V_U_ack_in_dummy;
wire    regslice_both_output_stream_V_keep_V_U_vld_out;
wire    regslice_both_output_stream_V_strb_V_U_apdone_blk;
wire    regslice_both_output_stream_V_strb_V_U_ack_in_dummy;
wire    regslice_both_output_stream_V_strb_V_U_vld_out;
wire    regslice_both_output_stream_V_user_V_U_apdone_blk;
wire    regslice_both_output_stream_V_user_V_U_ack_in_dummy;
wire    regslice_both_output_stream_V_user_V_U_vld_out;
wire    regslice_both_output_stream_V_last_V_U_apdone_blk;
reg   [0:0] output_stream_TLAST_int_regslice;
wire    regslice_both_output_stream_V_last_V_U_ack_in_dummy;
wire    regslice_both_output_stream_V_last_V_U_vld_out;
wire    regslice_both_output_stream_V_id_V_U_apdone_blk;
wire    regslice_both_output_stream_V_id_V_U_ack_in_dummy;
wire    regslice_both_output_stream_V_id_V_U_vld_out;
wire    regslice_both_output_stream_V_dest_V_U_apdone_blk;
wire    regslice_both_output_stream_V_dest_V_U_ack_in_dummy;
wire    regslice_both_output_stream_V_dest_V_U_vld_out;
wire    ap_ce_reg;
wire   [0:0] ap_return;

// power-on initialization
initial begin
#0 ap_CS_fsm = 14'd1;
#0 neuron_type_mem_0 = 6'd0;
#0 neuron_type_mem_1 = 6'd0;
#0 output_indexes_mem_0 = 4'd0;
#0 output_indexes_mem_1 = 4'd0;
#0 firings_mem_0 = 64'd0;
#0 grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_15_2_fu_296_ap_start_reg = 1'b0;
#0 grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_43_2_fu_318_ap_start_reg = 1'b0;
#0 grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_47_2_fu_326_ap_start_reg = 1'b0;
#0 grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_ap_start_reg = 1'b0;
#0 grp_snn_get_synaptic_conductances_fu_344_ap_start_reg = 1'b0;
end

hls_snn_izikevich_v_mem_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 12 ),
    .AddressWidth( 4 ))
v_mem_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(v_mem_address0),
    .ce0(v_mem_ce0),
    .we0(v_mem_we0),
    .d0(v_mem_d0),
    .q0(v_mem_q0),
    .address1(v_mem_address1),
    .ce1(v_mem_ce1),
    .q1(v_mem_q1)
);

hls_snn_izikevich_u_mem_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 12 ),
    .AddressWidth( 4 ))
u_mem_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(u_mem_address0),
    .ce0(u_mem_ce0),
    .we0(u_mem_we0),
    .d0(u_mem_d0),
    .address1(grp_snn_get_synaptic_conductances_fu_344_u_mem_address1),
    .ce1(u_mem_ce1),
    .q1(u_mem_q1)
);

hls_snn_izikevich_p_mem_RAM_AUTO_1R1W #(
    .DataWidth( 1 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
p_mem_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(p_mem_address0),
    .ce0(p_mem_ce0),
    .we0(p_mem_we0),
    .d0(grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_43_2_fu_318_p_mem_d0),
    .q0(p_mem_q0)
);

hls_snn_izikevich_v_mem_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 12 ),
    .AddressWidth( 4 ))
synapse_s_mem_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(synapse_s_mem_address0),
    .ce0(synapse_s_mem_ce0),
    .we0(synapse_s_mem_we0),
    .d0(grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_synapse_s_mem_d0),
    .q0(synapse_s_mem_q0),
    .address1(grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_synapse_s_mem_address1),
    .ce1(synapse_s_mem_ce1),
    .q1(synapse_s_mem_q1)
);

hls_snn_izikevich_hls_snn_izikevich_Pipeline_VITIS_LOOP_15_2 grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_15_2_fu_296(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_15_2_fu_296_ap_start),
    .ap_done(grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_15_2_fu_296_ap_done),
    .ap_idle(grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_15_2_fu_296_ap_idle),
    .ap_ready(grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_15_2_fu_296_ap_ready),
    .input_stream0_TVALID(input_stream0_TVALID_int_regslice),
    .input_stream0_TDATA(input_stream0_TDATA_int_regslice),
    .input_stream0_TREADY(grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_15_2_fu_296_input_stream0_TREADY),
    .input_stream0_TKEEP(input_stream0_TKEEP_int_regslice),
    .input_stream0_TSTRB(input_stream0_TSTRB_int_regslice),
    .input_stream0_TUSER(input_stream0_TUSER_int_regslice),
    .input_stream0_TLAST(input_stream0_TLAST_int_regslice),
    .input_stream0_TID(input_stream0_TID_int_regslice),
    .input_stream0_TDEST(input_stream0_TDEST_int_regslice),
    .neuron_type_mem_0_i(neuron_type_mem_0),
    .neuron_type_mem_0_o(grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_15_2_fu_296_neuron_type_mem_0_o),
    .neuron_type_mem_0_o_ap_vld(grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_15_2_fu_296_neuron_type_mem_0_o_ap_vld),
    .neuron_type_mem_1_i(neuron_type_mem_1),
    .neuron_type_mem_1_o(grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_15_2_fu_296_neuron_type_mem_1_o),
    .neuron_type_mem_1_o_ap_vld(grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_15_2_fu_296_neuron_type_mem_1_o_ap_vld)
);

hls_snn_izikevich_hls_snn_izikevich_Pipeline_VITIS_LOOP_43_2 grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_43_2_fu_318(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_43_2_fu_318_ap_start),
    .ap_done(grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_43_2_fu_318_ap_done),
    .ap_idle(grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_43_2_fu_318_ap_idle),
    .ap_ready(grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_43_2_fu_318_ap_ready),
    .p_input_load(p_input_read_reg_504),
    .p_mem_address0(grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_43_2_fu_318_p_mem_address0),
    .p_mem_ce0(grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_43_2_fu_318_p_mem_ce0),
    .p_mem_we0(grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_43_2_fu_318_p_mem_we0),
    .p_mem_d0(grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_43_2_fu_318_p_mem_d0)
);

hls_snn_izikevich_hls_snn_izikevich_Pipeline_VITIS_LOOP_47_2 grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_47_2_fu_326(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_47_2_fu_326_ap_start),
    .ap_done(grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_47_2_fu_326_ap_done),
    .ap_idle(grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_47_2_fu_326_ap_idle),
    .ap_ready(grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_47_2_fu_326_ap_ready),
    .v_mem_address0(grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_47_2_fu_326_v_mem_address0),
    .v_mem_ce0(grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_47_2_fu_326_v_mem_ce0),
    .v_mem_we0(grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_47_2_fu_326_v_mem_we0),
    .v_mem_d0(grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_47_2_fu_326_v_mem_d0),
    .u_mem_address0(grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_47_2_fu_326_u_mem_address0),
    .u_mem_ce0(grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_47_2_fu_326_u_mem_ce0),
    .u_mem_we0(grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_47_2_fu_326_u_mem_we0),
    .u_mem_d0(grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_47_2_fu_326_u_mem_d0)
);

hls_snn_izikevich_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1 grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_ap_start),
    .ap_done(grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_ap_done),
    .ap_idle(grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_ap_idle),
    .ap_ready(grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_ap_ready),
    .synapse_s_mem_address0(grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_synapse_s_mem_address0),
    .synapse_s_mem_ce0(grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_synapse_s_mem_ce0),
    .synapse_s_mem_we0(grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_synapse_s_mem_we0),
    .synapse_s_mem_d0(grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_synapse_s_mem_d0),
    .synapse_s_mem_address1(grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_synapse_s_mem_address1),
    .synapse_s_mem_ce1(grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_synapse_s_mem_ce1),
    .synapse_s_mem_q1(synapse_s_mem_q1),
    .v_mem_address0(grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_v_mem_address0),
    .v_mem_ce0(grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_v_mem_ce0),
    .v_mem_q0(v_mem_q0),
    .p_mem_address0(grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_p_mem_address0),
    .p_mem_ce0(grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_p_mem_ce0),
    .p_mem_q0(p_mem_q0),
    .grp_fu_537_p_din0(grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_grp_fu_537_p_din0),
    .grp_fu_537_p_din1(grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_grp_fu_537_p_din1),
    .grp_fu_537_p_opcode(grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_grp_fu_537_p_opcode),
    .grp_fu_537_p_dout0(grp_fu_537_p2),
    .grp_fu_537_p_ce(grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_grp_fu_537_p_ce),
    .grp_fu_541_p_din0(grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_grp_fu_541_p_din0),
    .grp_fu_541_p_din1(grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_grp_fu_541_p_din1),
    .grp_fu_541_p_dout0(grp_fu_541_p2),
    .grp_fu_541_p_ce(grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_grp_fu_541_p_ce)
);

hls_snn_izikevich_snn_get_synaptic_conductances grp_snn_get_synaptic_conductances_fu_344(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_snn_get_synaptic_conductances_fu_344_ap_start),
    .ap_done(grp_snn_get_synaptic_conductances_fu_344_ap_done),
    .ap_idle(grp_snn_get_synaptic_conductances_fu_344_ap_idle),
    .ap_ready(grp_snn_get_synaptic_conductances_fu_344_ap_ready),
    .input_stream0_TDATA(input_stream0_TDATA_int_regslice),
    .input_stream0_TVALID(input_stream0_TVALID_int_regslice),
    .input_stream0_TREADY(grp_snn_get_synaptic_conductances_fu_344_input_stream0_TREADY),
    .input_stream0_TKEEP(input_stream0_TKEEP_int_regslice),
    .input_stream0_TSTRB(input_stream0_TSTRB_int_regslice),
    .input_stream0_TUSER(input_stream0_TUSER_int_regslice),
    .input_stream0_TLAST(input_stream0_TLAST_int_regslice),
    .input_stream0_TID(input_stream0_TID_int_regslice),
    .input_stream0_TDEST(input_stream0_TDEST_int_regslice),
    .input_stream1_TDATA(input_stream1_TDATA_int_regslice),
    .input_stream1_TVALID(input_stream1_TVALID_int_regslice),
    .input_stream1_TREADY(grp_snn_get_synaptic_conductances_fu_344_input_stream1_TREADY),
    .input_stream1_TKEEP(input_stream1_TKEEP_int_regslice),
    .input_stream1_TSTRB(input_stream1_TSTRB_int_regslice),
    .input_stream1_TUSER(input_stream1_TUSER_int_regslice),
    .input_stream1_TLAST(input_stream1_TLAST_int_regslice),
    .input_stream1_TID(input_stream1_TID_int_regslice),
    .input_stream1_TDEST(input_stream1_TDEST_int_regslice),
    .input_stream2_TDATA(input_stream2_TDATA_int_regslice),
    .input_stream2_TVALID(input_stream2_TVALID_int_regslice),
    .input_stream2_TREADY(grp_snn_get_synaptic_conductances_fu_344_input_stream2_TREADY),
    .input_stream2_TKEEP(input_stream2_TKEEP_int_regslice),
    .input_stream2_TSTRB(input_stream2_TSTRB_int_regslice),
    .input_stream2_TUSER(input_stream2_TUSER_int_regslice),
    .input_stream2_TLAST(input_stream2_TLAST_int_regslice),
    .input_stream2_TID(input_stream2_TID_int_regslice),
    .input_stream2_TDEST(input_stream2_TDEST_int_regslice),
    .input_stream3_TDATA(input_stream3_TDATA_int_regslice),
    .input_stream3_TVALID(input_stream3_TVALID_int_regslice),
    .input_stream3_TREADY(grp_snn_get_synaptic_conductances_fu_344_input_stream3_TREADY),
    .input_stream3_TKEEP(input_stream3_TKEEP_int_regslice),
    .input_stream3_TSTRB(input_stream3_TSTRB_int_regslice),
    .input_stream3_TUSER(input_stream3_TUSER_int_regslice),
    .input_stream3_TLAST(input_stream3_TLAST_int_regslice),
    .input_stream3_TID(input_stream3_TID_int_regslice),
    .input_stream3_TDEST(input_stream3_TDEST_int_regslice),
    .neuron_type_mem_0(neuron_type_mem_0),
    .neuron_type_mem_1(neuron_type_mem_1),
    .synapse_s_mem_address0(grp_snn_get_synaptic_conductances_fu_344_synapse_s_mem_address0),
    .synapse_s_mem_ce0(grp_snn_get_synaptic_conductances_fu_344_synapse_s_mem_ce0),
    .synapse_s_mem_q0(synapse_s_mem_q0),
    .u_mem_address0(grp_snn_get_synaptic_conductances_fu_344_u_mem_address0),
    .u_mem_ce0(grp_snn_get_synaptic_conductances_fu_344_u_mem_ce0),
    .u_mem_we0(grp_snn_get_synaptic_conductances_fu_344_u_mem_we0),
    .u_mem_d0(grp_snn_get_synaptic_conductances_fu_344_u_mem_d0),
    .u_mem_address1(grp_snn_get_synaptic_conductances_fu_344_u_mem_address1),
    .u_mem_ce1(grp_snn_get_synaptic_conductances_fu_344_u_mem_ce1),
    .u_mem_q1(u_mem_q1),
    .firings_mem_0_i(firings_mem_0),
    .firings_mem_0_o(grp_snn_get_synaptic_conductances_fu_344_firings_mem_0_o),
    .firings_mem_0_o_ap_vld(grp_snn_get_synaptic_conductances_fu_344_firings_mem_0_o_ap_vld),
    .v_mem_address0(grp_snn_get_synaptic_conductances_fu_344_v_mem_address0),
    .v_mem_ce0(grp_snn_get_synaptic_conductances_fu_344_v_mem_ce0),
    .v_mem_we0(grp_snn_get_synaptic_conductances_fu_344_v_mem_we0),
    .v_mem_d0(grp_snn_get_synaptic_conductances_fu_344_v_mem_d0),
    .v_mem_q0(v_mem_q0),
    .grp_fu_537_p_din0(grp_snn_get_synaptic_conductances_fu_344_grp_fu_537_p_din0),
    .grp_fu_537_p_din1(grp_snn_get_synaptic_conductances_fu_344_grp_fu_537_p_din1),
    .grp_fu_537_p_opcode(grp_snn_get_synaptic_conductances_fu_344_grp_fu_537_p_opcode),
    .grp_fu_537_p_dout0(grp_fu_537_p2),
    .grp_fu_537_p_ce(grp_snn_get_synaptic_conductances_fu_344_grp_fu_537_p_ce),
    .grp_fu_541_p_din0(grp_snn_get_synaptic_conductances_fu_344_grp_fu_541_p_din0),
    .grp_fu_541_p_din1(grp_snn_get_synaptic_conductances_fu_344_grp_fu_541_p_din1),
    .grp_fu_541_p_dout0(grp_fu_541_p2),
    .grp_fu_541_p_ce(grp_snn_get_synaptic_conductances_fu_344_grp_fu_541_p_ce)
);

hls_snn_izikevich_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .ap_return(1'd1),
    .state(state),
    .p_input(p_input),
    .output_indexes_address0(output_indexes_address0),
    .output_indexes_ce0(output_indexes_ce0),
    .output_indexes_q0(output_indexes_q0)
);

hls_snn_izikevich_faddfsub_32ns_32ns_32_2_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
faddfsub_32ns_32ns_32_2_full_dsp_1_U114(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_537_p0),
    .din1(grp_fu_537_p1),
    .opcode(grp_fu_537_opcode),
    .ce(grp_fu_537_ce),
    .dout(grp_fu_537_p2)
);

hls_snn_izikevich_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U115(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_541_p0),
    .din1(grp_fu_541_p1),
    .ce(grp_fu_541_ce),
    .dout(grp_fu_541_p2)
);

hls_snn_izikevich_regslice_both #(
    .DataWidth( 64 ))
regslice_both_input_stream0_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_stream0_TDATA),
    .vld_in(input_stream0_TVALID),
    .ack_in(regslice_both_input_stream0_V_data_V_U_ack_in),
    .data_out(input_stream0_TDATA_int_regslice),
    .vld_out(input_stream0_TVALID_int_regslice),
    .ack_out(input_stream0_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream0_V_data_V_U_apdone_blk)
);

hls_snn_izikevich_regslice_both #(
    .DataWidth( 8 ))
regslice_both_input_stream0_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_stream0_TKEEP),
    .vld_in(input_stream0_TVALID),
    .ack_in(regslice_both_input_stream0_V_keep_V_U_ack_in),
    .data_out(input_stream0_TKEEP_int_regslice),
    .vld_out(regslice_both_input_stream0_V_keep_V_U_vld_out),
    .ack_out(input_stream0_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream0_V_keep_V_U_apdone_blk)
);

hls_snn_izikevich_regslice_both #(
    .DataWidth( 8 ))
regslice_both_input_stream0_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_stream0_TSTRB),
    .vld_in(input_stream0_TVALID),
    .ack_in(regslice_both_input_stream0_V_strb_V_U_ack_in),
    .data_out(input_stream0_TSTRB_int_regslice),
    .vld_out(regslice_both_input_stream0_V_strb_V_U_vld_out),
    .ack_out(input_stream0_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream0_V_strb_V_U_apdone_blk)
);

hls_snn_izikevich_regslice_both #(
    .DataWidth( 1 ))
regslice_both_input_stream0_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_stream0_TUSER),
    .vld_in(input_stream0_TVALID),
    .ack_in(regslice_both_input_stream0_V_user_V_U_ack_in),
    .data_out(input_stream0_TUSER_int_regslice),
    .vld_out(regslice_both_input_stream0_V_user_V_U_vld_out),
    .ack_out(input_stream0_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream0_V_user_V_U_apdone_blk)
);

hls_snn_izikevich_regslice_both #(
    .DataWidth( 1 ))
regslice_both_input_stream0_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_stream0_TLAST),
    .vld_in(input_stream0_TVALID),
    .ack_in(regslice_both_input_stream0_V_last_V_U_ack_in),
    .data_out(input_stream0_TLAST_int_regslice),
    .vld_out(regslice_both_input_stream0_V_last_V_U_vld_out),
    .ack_out(input_stream0_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream0_V_last_V_U_apdone_blk)
);

hls_snn_izikevich_regslice_both #(
    .DataWidth( 1 ))
regslice_both_input_stream0_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_stream0_TID),
    .vld_in(input_stream0_TVALID),
    .ack_in(regslice_both_input_stream0_V_id_V_U_ack_in),
    .data_out(input_stream0_TID_int_regslice),
    .vld_out(regslice_both_input_stream0_V_id_V_U_vld_out),
    .ack_out(input_stream0_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream0_V_id_V_U_apdone_blk)
);

hls_snn_izikevich_regslice_both #(
    .DataWidth( 1 ))
regslice_both_input_stream0_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_stream0_TDEST),
    .vld_in(input_stream0_TVALID),
    .ack_in(regslice_both_input_stream0_V_dest_V_U_ack_in),
    .data_out(input_stream0_TDEST_int_regslice),
    .vld_out(regslice_both_input_stream0_V_dest_V_U_vld_out),
    .ack_out(input_stream0_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream0_V_dest_V_U_apdone_blk)
);

hls_snn_izikevich_regslice_both #(
    .DataWidth( 64 ))
regslice_both_input_stream1_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_stream1_TDATA),
    .vld_in(input_stream1_TVALID),
    .ack_in(regslice_both_input_stream1_V_data_V_U_ack_in),
    .data_out(input_stream1_TDATA_int_regslice),
    .vld_out(input_stream1_TVALID_int_regslice),
    .ack_out(input_stream1_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream1_V_data_V_U_apdone_blk)
);

hls_snn_izikevich_regslice_both #(
    .DataWidth( 8 ))
regslice_both_input_stream1_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_stream1_TKEEP),
    .vld_in(input_stream1_TVALID),
    .ack_in(regslice_both_input_stream1_V_keep_V_U_ack_in),
    .data_out(input_stream1_TKEEP_int_regslice),
    .vld_out(regslice_both_input_stream1_V_keep_V_U_vld_out),
    .ack_out(input_stream1_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream1_V_keep_V_U_apdone_blk)
);

hls_snn_izikevich_regslice_both #(
    .DataWidth( 8 ))
regslice_both_input_stream1_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_stream1_TSTRB),
    .vld_in(input_stream1_TVALID),
    .ack_in(regslice_both_input_stream1_V_strb_V_U_ack_in),
    .data_out(input_stream1_TSTRB_int_regslice),
    .vld_out(regslice_both_input_stream1_V_strb_V_U_vld_out),
    .ack_out(input_stream1_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream1_V_strb_V_U_apdone_blk)
);

hls_snn_izikevich_regslice_both #(
    .DataWidth( 1 ))
regslice_both_input_stream1_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_stream1_TUSER),
    .vld_in(input_stream1_TVALID),
    .ack_in(regslice_both_input_stream1_V_user_V_U_ack_in),
    .data_out(input_stream1_TUSER_int_regslice),
    .vld_out(regslice_both_input_stream1_V_user_V_U_vld_out),
    .ack_out(input_stream1_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream1_V_user_V_U_apdone_blk)
);

hls_snn_izikevich_regslice_both #(
    .DataWidth( 1 ))
regslice_both_input_stream1_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_stream1_TLAST),
    .vld_in(input_stream1_TVALID),
    .ack_in(regslice_both_input_stream1_V_last_V_U_ack_in),
    .data_out(input_stream1_TLAST_int_regslice),
    .vld_out(regslice_both_input_stream1_V_last_V_U_vld_out),
    .ack_out(input_stream1_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream1_V_last_V_U_apdone_blk)
);

hls_snn_izikevich_regslice_both #(
    .DataWidth( 1 ))
regslice_both_input_stream1_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_stream1_TID),
    .vld_in(input_stream1_TVALID),
    .ack_in(regslice_both_input_stream1_V_id_V_U_ack_in),
    .data_out(input_stream1_TID_int_regslice),
    .vld_out(regslice_both_input_stream1_V_id_V_U_vld_out),
    .ack_out(input_stream1_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream1_V_id_V_U_apdone_blk)
);

hls_snn_izikevich_regslice_both #(
    .DataWidth( 1 ))
regslice_both_input_stream1_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_stream1_TDEST),
    .vld_in(input_stream1_TVALID),
    .ack_in(regslice_both_input_stream1_V_dest_V_U_ack_in),
    .data_out(input_stream1_TDEST_int_regslice),
    .vld_out(regslice_both_input_stream1_V_dest_V_U_vld_out),
    .ack_out(input_stream1_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream1_V_dest_V_U_apdone_blk)
);

hls_snn_izikevich_regslice_both #(
    .DataWidth( 64 ))
regslice_both_input_stream2_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_stream2_TDATA),
    .vld_in(input_stream2_TVALID),
    .ack_in(regslice_both_input_stream2_V_data_V_U_ack_in),
    .data_out(input_stream2_TDATA_int_regslice),
    .vld_out(input_stream2_TVALID_int_regslice),
    .ack_out(input_stream2_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream2_V_data_V_U_apdone_blk)
);

hls_snn_izikevich_regslice_both #(
    .DataWidth( 8 ))
regslice_both_input_stream2_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_stream2_TKEEP),
    .vld_in(input_stream2_TVALID),
    .ack_in(regslice_both_input_stream2_V_keep_V_U_ack_in),
    .data_out(input_stream2_TKEEP_int_regslice),
    .vld_out(regslice_both_input_stream2_V_keep_V_U_vld_out),
    .ack_out(input_stream2_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream2_V_keep_V_U_apdone_blk)
);

hls_snn_izikevich_regslice_both #(
    .DataWidth( 8 ))
regslice_both_input_stream2_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_stream2_TSTRB),
    .vld_in(input_stream2_TVALID),
    .ack_in(regslice_both_input_stream2_V_strb_V_U_ack_in),
    .data_out(input_stream2_TSTRB_int_regslice),
    .vld_out(regslice_both_input_stream2_V_strb_V_U_vld_out),
    .ack_out(input_stream2_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream2_V_strb_V_U_apdone_blk)
);

hls_snn_izikevich_regslice_both #(
    .DataWidth( 1 ))
regslice_both_input_stream2_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_stream2_TUSER),
    .vld_in(input_stream2_TVALID),
    .ack_in(regslice_both_input_stream2_V_user_V_U_ack_in),
    .data_out(input_stream2_TUSER_int_regslice),
    .vld_out(regslice_both_input_stream2_V_user_V_U_vld_out),
    .ack_out(input_stream2_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream2_V_user_V_U_apdone_blk)
);

hls_snn_izikevich_regslice_both #(
    .DataWidth( 1 ))
regslice_both_input_stream2_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_stream2_TLAST),
    .vld_in(input_stream2_TVALID),
    .ack_in(regslice_both_input_stream2_V_last_V_U_ack_in),
    .data_out(input_stream2_TLAST_int_regslice),
    .vld_out(regslice_both_input_stream2_V_last_V_U_vld_out),
    .ack_out(input_stream2_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream2_V_last_V_U_apdone_blk)
);

hls_snn_izikevich_regslice_both #(
    .DataWidth( 1 ))
regslice_both_input_stream2_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_stream2_TID),
    .vld_in(input_stream2_TVALID),
    .ack_in(regslice_both_input_stream2_V_id_V_U_ack_in),
    .data_out(input_stream2_TID_int_regslice),
    .vld_out(regslice_both_input_stream2_V_id_V_U_vld_out),
    .ack_out(input_stream2_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream2_V_id_V_U_apdone_blk)
);

hls_snn_izikevich_regslice_both #(
    .DataWidth( 1 ))
regslice_both_input_stream2_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_stream2_TDEST),
    .vld_in(input_stream2_TVALID),
    .ack_in(regslice_both_input_stream2_V_dest_V_U_ack_in),
    .data_out(input_stream2_TDEST_int_regslice),
    .vld_out(regslice_both_input_stream2_V_dest_V_U_vld_out),
    .ack_out(input_stream2_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream2_V_dest_V_U_apdone_blk)
);

hls_snn_izikevich_regslice_both #(
    .DataWidth( 64 ))
regslice_both_input_stream3_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_stream3_TDATA),
    .vld_in(input_stream3_TVALID),
    .ack_in(regslice_both_input_stream3_V_data_V_U_ack_in),
    .data_out(input_stream3_TDATA_int_regslice),
    .vld_out(input_stream3_TVALID_int_regslice),
    .ack_out(input_stream3_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream3_V_data_V_U_apdone_blk)
);

hls_snn_izikevich_regslice_both #(
    .DataWidth( 8 ))
regslice_both_input_stream3_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_stream3_TKEEP),
    .vld_in(input_stream3_TVALID),
    .ack_in(regslice_both_input_stream3_V_keep_V_U_ack_in),
    .data_out(input_stream3_TKEEP_int_regslice),
    .vld_out(regslice_both_input_stream3_V_keep_V_U_vld_out),
    .ack_out(input_stream3_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream3_V_keep_V_U_apdone_blk)
);

hls_snn_izikevich_regslice_both #(
    .DataWidth( 8 ))
regslice_both_input_stream3_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_stream3_TSTRB),
    .vld_in(input_stream3_TVALID),
    .ack_in(regslice_both_input_stream3_V_strb_V_U_ack_in),
    .data_out(input_stream3_TSTRB_int_regslice),
    .vld_out(regslice_both_input_stream3_V_strb_V_U_vld_out),
    .ack_out(input_stream3_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream3_V_strb_V_U_apdone_blk)
);

hls_snn_izikevich_regslice_both #(
    .DataWidth( 1 ))
regslice_both_input_stream3_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_stream3_TUSER),
    .vld_in(input_stream3_TVALID),
    .ack_in(regslice_both_input_stream3_V_user_V_U_ack_in),
    .data_out(input_stream3_TUSER_int_regslice),
    .vld_out(regslice_both_input_stream3_V_user_V_U_vld_out),
    .ack_out(input_stream3_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream3_V_user_V_U_apdone_blk)
);

hls_snn_izikevich_regslice_both #(
    .DataWidth( 1 ))
regslice_both_input_stream3_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_stream3_TLAST),
    .vld_in(input_stream3_TVALID),
    .ack_in(regslice_both_input_stream3_V_last_V_U_ack_in),
    .data_out(input_stream3_TLAST_int_regslice),
    .vld_out(regslice_both_input_stream3_V_last_V_U_vld_out),
    .ack_out(input_stream3_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream3_V_last_V_U_apdone_blk)
);

hls_snn_izikevich_regslice_both #(
    .DataWidth( 1 ))
regslice_both_input_stream3_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_stream3_TID),
    .vld_in(input_stream3_TVALID),
    .ack_in(regslice_both_input_stream3_V_id_V_U_ack_in),
    .data_out(input_stream3_TID_int_regslice),
    .vld_out(regslice_both_input_stream3_V_id_V_U_vld_out),
    .ack_out(input_stream3_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream3_V_id_V_U_apdone_blk)
);

hls_snn_izikevich_regslice_both #(
    .DataWidth( 1 ))
regslice_both_input_stream3_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_stream3_TDEST),
    .vld_in(input_stream3_TVALID),
    .ack_in(regslice_both_input_stream3_V_dest_V_U_ack_in),
    .data_out(input_stream3_TDEST_int_regslice),
    .vld_out(regslice_both_input_stream3_V_dest_V_U_vld_out),
    .ack_out(input_stream3_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream3_V_dest_V_U_apdone_blk)
);

hls_snn_izikevich_regslice_both #(
    .DataWidth( 64 ))
regslice_both_output_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(output_stream_TDATA_int_regslice),
    .vld_in(output_stream_TVALID_int_regslice),
    .ack_in(output_stream_TREADY_int_regslice),
    .data_out(output_stream_TDATA),
    .vld_out(regslice_both_output_stream_V_data_V_U_vld_out),
    .ack_out(output_stream_TREADY),
    .apdone_blk(regslice_both_output_stream_V_data_V_U_apdone_blk)
);

hls_snn_izikevich_regslice_both #(
    .DataWidth( 8 ))
regslice_both_output_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(8'd0),
    .vld_in(output_stream_TVALID_int_regslice),
    .ack_in(regslice_both_output_stream_V_keep_V_U_ack_in_dummy),
    .data_out(output_stream_TKEEP),
    .vld_out(regslice_both_output_stream_V_keep_V_U_vld_out),
    .ack_out(output_stream_TREADY),
    .apdone_blk(regslice_both_output_stream_V_keep_V_U_apdone_blk)
);

hls_snn_izikevich_regslice_both #(
    .DataWidth( 8 ))
regslice_both_output_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(8'd0),
    .vld_in(output_stream_TVALID_int_regslice),
    .ack_in(regslice_both_output_stream_V_strb_V_U_ack_in_dummy),
    .data_out(output_stream_TSTRB),
    .vld_out(regslice_both_output_stream_V_strb_V_U_vld_out),
    .ack_out(output_stream_TREADY),
    .apdone_blk(regslice_both_output_stream_V_strb_V_U_apdone_blk)
);

hls_snn_izikevich_regslice_both #(
    .DataWidth( 1 ))
regslice_both_output_stream_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(1'd0),
    .vld_in(output_stream_TVALID_int_regslice),
    .ack_in(regslice_both_output_stream_V_user_V_U_ack_in_dummy),
    .data_out(output_stream_TUSER),
    .vld_out(regslice_both_output_stream_V_user_V_U_vld_out),
    .ack_out(output_stream_TREADY),
    .apdone_blk(regslice_both_output_stream_V_user_V_U_apdone_blk)
);

hls_snn_izikevich_regslice_both #(
    .DataWidth( 1 ))
regslice_both_output_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(output_stream_TLAST_int_regslice),
    .vld_in(output_stream_TVALID_int_regslice),
    .ack_in(regslice_both_output_stream_V_last_V_U_ack_in_dummy),
    .data_out(output_stream_TLAST),
    .vld_out(regslice_both_output_stream_V_last_V_U_vld_out),
    .ack_out(output_stream_TREADY),
    .apdone_blk(regslice_both_output_stream_V_last_V_U_apdone_blk)
);

hls_snn_izikevich_regslice_both #(
    .DataWidth( 1 ))
regslice_both_output_stream_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(1'd0),
    .vld_in(output_stream_TVALID_int_regslice),
    .ack_in(regslice_both_output_stream_V_id_V_U_ack_in_dummy),
    .data_out(output_stream_TID),
    .vld_out(regslice_both_output_stream_V_id_V_U_vld_out),
    .ack_out(output_stream_TREADY),
    .apdone_blk(regslice_both_output_stream_V_id_V_U_apdone_blk)
);

hls_snn_izikevich_regslice_both #(
    .DataWidth( 1 ))
regslice_both_output_stream_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(1'd0),
    .vld_in(output_stream_TVALID_int_regslice),
    .ack_in(regslice_both_output_stream_V_dest_V_U_ack_in_dummy),
    .data_out(output_stream_TDEST),
    .vld_out(regslice_both_output_stream_V_dest_V_U_vld_out),
    .ack_out(output_stream_TREADY),
    .apdone_blk(regslice_both_output_stream_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_15_2_fu_296_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (state_read_read_fu_204_p2 == 1'd0))) begin
            grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_15_2_fu_296_ap_start_reg <= 1'b1;
        end else if ((grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_15_2_fu_296_ap_ready == 1'b1)) begin
            grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_15_2_fu_296_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_43_2_fu_318_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (state_read_read_fu_204_p2 == 1'd1))) begin
            grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_43_2_fu_318_ap_start_reg <= 1'b1;
        end else if ((grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_43_2_fu_318_ap_ready == 1'b1)) begin
            grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_43_2_fu_318_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_47_2_fu_326_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_47_2_fu_326_ap_start_reg <= 1'b1;
        end else if ((grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_47_2_fu_326_ap_ready == 1'b1)) begin
            grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_47_2_fu_326_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_ap_start_reg <= 1'b1;
        end else if ((grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_ap_ready == 1'b1)) begin
            grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_snn_get_synaptic_conductances_fu_344_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_snn_get_synaptic_conductances_fu_344_ap_start_reg <= 1'b1;
        end else if ((grp_snn_get_synaptic_conductances_fu_344_ap_ready == 1'b1)) begin
            grp_snn_get_synaptic_conductances_fu_344_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_snn_get_synaptic_conductances_fu_344_firings_mem_0_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10) & (state_read_reg_500 == 1'd1))) begin
        firings_mem_0 <= grp_snn_get_synaptic_conductances_fu_344_firings_mem_0_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_15_2_fu_296_neuron_type_mem_0_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        neuron_type_mem_0 <= grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_15_2_fu_296_neuron_type_mem_0_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_15_2_fu_296_neuron_type_mem_1_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        neuron_type_mem_1 <= grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_15_2_fu_296_neuron_type_mem_1_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_47_2_fu_326_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        output_indexes_mem_0 <= trunc_ln43_fu_440_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        output_indexes_mem_1 <= trunc_ln43_1_fu_450_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (state_read_read_fu_204_p2 == 1'd1))) begin
        p_input_read_reg_504 <= p_input;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        state_read_reg_500 <= state;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state10_on_subcall_done)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((output_stream_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

always @ (*) begin
    if ((output_stream_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

always @ (*) begin
    if (((output_stream_TREADY_int_regslice == 1'b0) | (regslice_both_output_stream_V_data_V_U_apdone_blk == 1'b1))) begin
        ap_ST_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_fsm_state14_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_15_2_fu_296_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_47_2_fu_326_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_43_2_fu_318_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((~((output_stream_TREADY_int_regslice == 1'b0) | (regslice_both_output_stream_V_data_V_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state14))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((output_stream_TREADY_int_regslice == 1'b0) | (regslice_both_output_stream_V_data_V_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state14))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_537_ce = grp_snn_get_synaptic_conductances_fu_344_grp_fu_537_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_537_ce = grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_grp_fu_537_p_ce;
    end else begin
        grp_fu_537_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_537_opcode = grp_snn_get_synaptic_conductances_fu_344_grp_fu_537_p_opcode;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_537_opcode = grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_grp_fu_537_p_opcode;
    end else begin
        grp_fu_537_opcode = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_537_p0 = grp_snn_get_synaptic_conductances_fu_344_grp_fu_537_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_537_p0 = grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_grp_fu_537_p_din0;
    end else begin
        grp_fu_537_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_537_p1 = grp_snn_get_synaptic_conductances_fu_344_grp_fu_537_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_537_p1 = grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_grp_fu_537_p_din1;
    end else begin
        grp_fu_537_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_541_ce = grp_snn_get_synaptic_conductances_fu_344_grp_fu_541_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_541_ce = grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_grp_fu_541_p_ce;
    end else begin
        grp_fu_541_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_541_p0 = grp_snn_get_synaptic_conductances_fu_344_grp_fu_541_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_541_p0 = grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_grp_fu_541_p_din0;
    end else begin
        grp_fu_541_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_541_p1 = grp_snn_get_synaptic_conductances_fu_344_grp_fu_541_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_541_p1 = grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_grp_fu_541_p_din1;
    end else begin
        grp_fu_541_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & (state_read_reg_500 == 1'd1))) begin
        input_stream0_TREADY_int_regslice = grp_snn_get_synaptic_conductances_fu_344_input_stream0_TREADY;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_stream0_TREADY_int_regslice = grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_15_2_fu_296_input_stream0_TREADY;
    end else begin
        input_stream0_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & (state_read_reg_500 == 1'd1))) begin
        input_stream1_TREADY_int_regslice = grp_snn_get_synaptic_conductances_fu_344_input_stream1_TREADY;
    end else begin
        input_stream1_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & (state_read_reg_500 == 1'd1))) begin
        input_stream2_TREADY_int_regslice = grp_snn_get_synaptic_conductances_fu_344_input_stream2_TREADY;
    end else begin
        input_stream2_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & (state_read_reg_500 == 1'd1))) begin
        input_stream3_TREADY_int_regslice = grp_snn_get_synaptic_conductances_fu_344_input_stream3_TREADY;
    end else begin
        input_stream3_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        output_indexes_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        output_indexes_address0 = 64'd0;
    end else begin
        output_indexes_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_47_2_fu_326_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4)))) begin
        output_indexes_ce0 = 1'b1;
    end else begin
        output_indexes_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12))) begin
        output_stream_TDATA_blk_n = output_stream_TREADY_int_regslice;
    end else begin
        output_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((output_stream_TREADY_int_regslice == 1'b1)) begin
        if ((1'b1 == ap_CS_fsm_state13)) begin
            output_stream_TDATA_int_regslice = firings_mem_0;
        end else if ((1'b1 == ap_CS_fsm_state12)) begin
            output_stream_TDATA_int_regslice = c_fu_486_p3;
        end else begin
            output_stream_TDATA_int_regslice = 'bx;
        end
    end else begin
        output_stream_TDATA_int_regslice = 'bx;
    end
end

always @ (*) begin
    if ((output_stream_TREADY_int_regslice == 1'b1)) begin
        if ((1'b1 == ap_CS_fsm_state13)) begin
            output_stream_TLAST_int_regslice = 1'd1;
        end else if ((1'b1 == ap_CS_fsm_state12)) begin
            output_stream_TLAST_int_regslice = 1'd0;
        end else begin
            output_stream_TLAST_int_regslice = 'bx;
        end
    end else begin
        output_stream_TLAST_int_regslice = 'bx;
    end
end

always @ (*) begin
    if ((((output_stream_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state13)) | ((output_stream_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state12)))) begin
        output_stream_TVALID_int_regslice = 1'b1;
    end else begin
        output_stream_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        p_mem_address0 = grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_p_mem_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        p_mem_address0 = grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_43_2_fu_318_p_mem_address0;
    end else begin
        p_mem_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        p_mem_ce0 = grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_p_mem_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        p_mem_ce0 = grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_43_2_fu_318_p_mem_ce0;
    end else begin
        p_mem_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        p_mem_we0 = grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_43_2_fu_318_p_mem_we0;
    end else begin
        p_mem_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & (state_read_reg_500 == 1'd1))) begin
        synapse_s_mem_address0 = grp_snn_get_synaptic_conductances_fu_344_synapse_s_mem_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        synapse_s_mem_address0 = grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_synapse_s_mem_address0;
    end else begin
        synapse_s_mem_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & (state_read_reg_500 == 1'd1))) begin
        synapse_s_mem_ce0 = grp_snn_get_synaptic_conductances_fu_344_synapse_s_mem_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        synapse_s_mem_ce0 = grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_synapse_s_mem_ce0;
    end else begin
        synapse_s_mem_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        synapse_s_mem_ce1 = grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_synapse_s_mem_ce1;
    end else begin
        synapse_s_mem_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        synapse_s_mem_we0 = grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_synapse_s_mem_we0;
    end else begin
        synapse_s_mem_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & (state_read_reg_500 == 1'd1))) begin
        u_mem_address0 = grp_snn_get_synaptic_conductances_fu_344_u_mem_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        u_mem_address0 = grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_47_2_fu_326_u_mem_address0;
    end else begin
        u_mem_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & (state_read_reg_500 == 1'd1))) begin
        u_mem_ce0 = grp_snn_get_synaptic_conductances_fu_344_u_mem_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        u_mem_ce0 = grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_47_2_fu_326_u_mem_ce0;
    end else begin
        u_mem_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & (state_read_reg_500 == 1'd1))) begin
        u_mem_ce1 = grp_snn_get_synaptic_conductances_fu_344_u_mem_ce1;
    end else begin
        u_mem_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & (state_read_reg_500 == 1'd1))) begin
        u_mem_d0 = grp_snn_get_synaptic_conductances_fu_344_u_mem_d0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        u_mem_d0 = grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_47_2_fu_326_u_mem_d0;
    end else begin
        u_mem_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & (state_read_reg_500 == 1'd1))) begin
        u_mem_we0 = grp_snn_get_synaptic_conductances_fu_344_u_mem_we0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        u_mem_we0 = grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_47_2_fu_326_u_mem_we0;
    end else begin
        u_mem_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        v_mem_address0 = zext_ln74_1_fu_473_p1;
    end else if (((1'b1 == ap_CS_fsm_state10) & (state_read_reg_500 == 1'd1))) begin
        v_mem_address0 = grp_snn_get_synaptic_conductances_fu_344_v_mem_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        v_mem_address0 = grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_v_mem_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v_mem_address0 = grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_47_2_fu_326_v_mem_address0;
    end else begin
        v_mem_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        v_mem_ce0 = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state10) & (state_read_reg_500 == 1'd1))) begin
        v_mem_ce0 = grp_snn_get_synaptic_conductances_fu_344_v_mem_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        v_mem_ce0 = grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_v_mem_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v_mem_ce0 = grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_47_2_fu_326_v_mem_ce0;
    end else begin
        v_mem_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        v_mem_ce1 = 1'b1;
    end else begin
        v_mem_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & (state_read_reg_500 == 1'd1))) begin
        v_mem_d0 = grp_snn_get_synaptic_conductances_fu_344_v_mem_d0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v_mem_d0 = grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_47_2_fu_326_v_mem_d0;
    end else begin
        v_mem_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & (state_read_reg_500 == 1'd1))) begin
        v_mem_we0 = grp_snn_get_synaptic_conductances_fu_344_v_mem_we0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v_mem_we0 = grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_47_2_fu_326_v_mem_we0;
    end else begin
        v_mem_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (state_read_read_fu_204_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (state_read_read_fu_204_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_15_2_fu_296_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_47_2_fu_326_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_43_2_fu_318_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b0 == ap_block_state10_on_subcall_done) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((output_stream_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            if (((output_stream_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            if ((~((output_stream_TREADY_int_regslice == 1'b0) | (regslice_both_output_stream_V_data_V_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state10_on_subcall_done = ((grp_snn_get_synaptic_conductances_fu_344_ap_done == 1'b0) & (state_read_reg_500 == 1'd1));
end

always @ (*) begin
    ap_block_state14 = ((output_stream_TREADY_int_regslice == 1'b0) | (regslice_both_output_stream_V_data_V_U_apdone_blk == 1'b1));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign bitcast_ln109_fu_478_p1 = v_mem_q1;

assign bitcast_ln110_fu_482_p1 = v_mem_q0;

assign c_fu_486_p3 = {{bitcast_ln110_fu_482_p1}, {bitcast_ln109_fu_478_p1}};

assign grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_15_2_fu_296_ap_start = grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_15_2_fu_296_ap_start_reg;

assign grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_43_2_fu_318_ap_start = grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_43_2_fu_318_ap_start_reg;

assign grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_47_2_fu_326_ap_start = grp_hls_snn_izikevich_Pipeline_VITIS_LOOP_47_2_fu_326_ap_start_reg;

assign grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_ap_start = grp_hls_snn_izikevich_Pipeline_synapses_layer_updates_VITIS_LOOP_22_1_fu_334_ap_start_reg;

assign grp_snn_get_synaptic_conductances_fu_344_ap_start = grp_snn_get_synaptic_conductances_fu_344_ap_start_reg;

assign input_stream0_TREADY = regslice_both_input_stream0_V_data_V_U_ack_in;

assign input_stream1_TREADY = regslice_both_input_stream1_V_data_V_U_ack_in;

assign input_stream2_TREADY = regslice_both_input_stream2_V_data_V_U_ack_in;

assign input_stream3_TREADY = regslice_both_input_stream3_V_data_V_U_ack_in;

assign output_stream_TVALID = regslice_both_output_stream_V_data_V_U_vld_out;

assign state_read_read_fu_204_p2 = state;

assign trunc_ln43_1_fu_450_p1 = output_indexes_q0[3:0];

assign trunc_ln43_fu_440_p1 = output_indexes_q0[3:0];

assign v_mem_address1 = zext_ln74_fu_464_p1;

assign zext_ln74_1_fu_473_p1 = output_indexes_mem_1;

assign zext_ln74_fu_464_p1 = output_indexes_mem_0;


reg find_kernel_block = 0;
// synthesis translate_off
`include "hls_snn_izikevich_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //hls_snn_izikevich

