// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module hls_snn_izikevich_snn_get_synaptic_conductances_Pipeline_input_synapses_cache (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11,
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11_ap_vld,
        synapse_s_mem_address0,
        synapse_s_mem_ce0,
        synapse_s_mem_q0,
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9,
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9_ap_vld,
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8,
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8_ap_vld,
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7,
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7_ap_vld,
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6,
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6_ap_vld,
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10,
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [31:0] snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11;
output   snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11_ap_vld;
output  [3:0] synapse_s_mem_address0;
output   synapse_s_mem_ce0;
input  [31:0] synapse_s_mem_q0;
output  [31:0] snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9;
output   snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9_ap_vld;
output  [31:0] snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8;
output   snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8_ap_vld;
output  [31:0] snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7;
output   snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7_ap_vld;
output  [31:0] snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6;
output   snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6_ap_vld;
output  [31:0] snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10;
output   snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10_ap_vld;

reg ap_idle;
reg snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11_ap_vld;
reg synapse_s_mem_ce0;
reg snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9_ap_vld;
reg snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8_ap_vld;
reg snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7_ap_vld;
reg snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6_ap_vld;
reg snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln150_fu_73_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [2:0] y_1_reg_148;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln151_1_fu_95_p1;
wire    ap_block_pp0_stage0;
reg   [2:0] y_fu_48;
wire   [2:0] add_ln150_fu_79_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_y_1;
wire   [3:0] zext_ln151_fu_85_p1;
wire   [3:0] add_ln151_fu_89_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

hls_snn_izikevich_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln150_fu_73_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            y_fu_48 <= add_ln150_fu_79_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            y_fu_48 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        y_1_reg_148 <= ap_sig_allocacmp_y_1;
    end
end

always @ (*) begin
    if (((icmp_ln150_fu_73_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_y_1 = 3'd0;
    end else begin
        ap_sig_allocacmp_y_1 = y_fu_48;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & ((y_1_reg_148 == 3'd5) | ((y_1_reg_148 == 3'd6) | (y_1_reg_148 == 3'd7))))) begin
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10_ap_vld = 1'b1;
    end else begin
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((y_1_reg_148 == 3'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11_ap_vld = 1'b1;
    end else begin
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((y_1_reg_148 == 3'd4) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6_ap_vld = 1'b1;
    end else begin
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((y_1_reg_148 == 3'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7_ap_vld = 1'b1;
    end else begin
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((y_1_reg_148 == 3'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8_ap_vld = 1'b1;
    end else begin
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((y_1_reg_148 == 3'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9_ap_vld = 1'b1;
    end else begin
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        synapse_s_mem_ce0 = 1'b1;
    end else begin
        synapse_s_mem_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln150_fu_79_p2 = (ap_sig_allocacmp_y_1 + 3'd1);

assign add_ln151_fu_89_p2 = (zext_ln151_fu_85_p1 + 4'd6);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln150_fu_73_p2 = ((ap_sig_allocacmp_y_1 == 3'd6) ? 1'b1 : 1'b0);

assign snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10 = synapse_s_mem_q0;

assign snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11 = synapse_s_mem_q0;

assign snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6 = synapse_s_mem_q0;

assign snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7 = synapse_s_mem_q0;

assign snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8 = synapse_s_mem_q0;

assign snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9 = synapse_s_mem_q0;

assign synapse_s_mem_address0 = zext_ln151_1_fu_95_p1;

assign zext_ln151_1_fu_95_p1 = add_ln151_fu_89_p2;

assign zext_ln151_fu_85_p1 = ap_sig_allocacmp_y_1;

endmodule //hls_snn_izikevich_snn_get_synaptic_conductances_Pipeline_input_synapses_cache
