
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2023.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2024 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xhls_snn_izikevich.h"

/*
* The configuration table for devices
*/

XHls_snn_izikevich_Config XHls_snn_izikevich_ConfigTable[XPAR_XHLS_SNN_IZIKEVICH_NUM_INSTANCES] =
{
	{
		XPAR_HLS_SNN_IZIKEVICH_0_DEVICE_ID,
		XPAR_HLS_SNN_IZIKEVICH_0_S_AXI_CONTROL_BASEADDR
	}
};


