-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity hls_snn_izikevich_snn_get_synaptic_conductances is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_stream0_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
    input_stream0_TVALID : IN STD_LOGIC;
    input_stream0_TREADY : OUT STD_LOGIC;
    input_stream0_TKEEP : IN STD_LOGIC_VECTOR (7 downto 0);
    input_stream0_TSTRB : IN STD_LOGIC_VECTOR (7 downto 0);
    input_stream0_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    input_stream1_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
    input_stream1_TVALID : IN STD_LOGIC;
    input_stream1_TREADY : OUT STD_LOGIC;
    input_stream1_TKEEP : IN STD_LOGIC_VECTOR (7 downto 0);
    input_stream1_TSTRB : IN STD_LOGIC_VECTOR (7 downto 0);
    input_stream1_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    input_stream2_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
    input_stream2_TVALID : IN STD_LOGIC;
    input_stream2_TREADY : OUT STD_LOGIC;
    input_stream2_TKEEP : IN STD_LOGIC_VECTOR (7 downto 0);
    input_stream2_TSTRB : IN STD_LOGIC_VECTOR (7 downto 0);
    input_stream2_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    input_stream3_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
    input_stream3_TVALID : IN STD_LOGIC;
    input_stream3_TREADY : OUT STD_LOGIC;
    input_stream3_TKEEP : IN STD_LOGIC_VECTOR (7 downto 0);
    input_stream3_TSTRB : IN STD_LOGIC_VECTOR (7 downto 0);
    input_stream3_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    neuron_type_mem_0 : IN STD_LOGIC_VECTOR (5 downto 0);
    neuron_type_mem_1 : IN STD_LOGIC_VECTOR (5 downto 0);
    synapse_s_mem_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    synapse_s_mem_ce0 : OUT STD_LOGIC;
    synapse_s_mem_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    u_mem_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    u_mem_ce0 : OUT STD_LOGIC;
    u_mem_we0 : OUT STD_LOGIC;
    u_mem_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    u_mem_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    u_mem_ce1 : OUT STD_LOGIC;
    u_mem_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    firings_mem_0_i : IN STD_LOGIC_VECTOR (63 downto 0);
    firings_mem_0_o : OUT STD_LOGIC_VECTOR (63 downto 0);
    firings_mem_0_o_ap_vld : OUT STD_LOGIC;
    v_mem_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    v_mem_ce0 : OUT STD_LOGIC;
    v_mem_we0 : OUT STD_LOGIC;
    v_mem_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    v_mem_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_465_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_465_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_465_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
    grp_fu_465_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_465_p_ce : OUT STD_LOGIC;
    grp_fu_469_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_469_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_469_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_469_p_ce : OUT STD_LOGIC );
end;


architecture behav of hls_snn_izikevich_snn_get_synaptic_conductances is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_ap_start : STD_LOGIC;
    signal grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_ap_done : STD_LOGIC;
    signal grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_ap_idle : STD_LOGIC;
    signal grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_ap_ready : STD_LOGIC;
    signal grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11_ap_vld : STD_LOGIC;
    signal grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_synapse_s_mem_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_synapse_s_mem_ce0 : STD_LOGIC;
    signal grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9_ap_vld : STD_LOGIC;
    signal grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8_ap_vld : STD_LOGIC;
    signal grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7_ap_vld : STD_LOGIC;
    signal grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6_ap_vld : STD_LOGIC;
    signal grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10_ap_vld : STD_LOGIC;
    signal grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_ap_start : STD_LOGIC;
    signal grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_ap_done : STD_LOGIC;
    signal grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_ap_idle : STD_LOGIC;
    signal grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_ap_ready : STD_LOGIC;
    signal grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_input_stream0_TREADY : STD_LOGIC;
    signal grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_input_stream1_TREADY : STD_LOGIC;
    signal grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_input_stream2_TREADY : STD_LOGIC;
    signal grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_input_stream3_TREADY : STD_LOGIC;
    signal grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_u_mem_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_u_mem_ce0 : STD_LOGIC;
    signal grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_u_mem_we0 : STD_LOGIC;
    signal grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_u_mem_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_u_mem_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_u_mem_ce1 : STD_LOGIC;
    signal grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_firings_mem_0_o : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_firings_mem_0_o_ap_vld : STD_LOGIC;
    signal grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_v_mem_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_v_mem_ce0 : STD_LOGIC;
    signal grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_v_mem_we0 : STD_LOGIC;
    signal grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_v_mem_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11_o : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11_o_ap_vld : STD_LOGIC;
    signal grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9_o : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9_o_ap_vld : STD_LOGIC;
    signal grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8_o : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8_o_ap_vld : STD_LOGIC;
    signal grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7_o : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7_o_ap_vld : STD_LOGIC;
    signal grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6_o : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6_o_ap_vld : STD_LOGIC;
    signal grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10_o : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10_o_ap_vld : STD_LOGIC;
    signal grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_synapse_s_mem_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_synapse_s_mem_ce0 : STD_LOGIC;
    signal grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_grp_fu_202_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_grp_fu_202_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_grp_fu_202_p_opcode : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_grp_fu_202_p_ce : STD_LOGIC;
    signal grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_grp_fu_206_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_grp_fu_206_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_grp_fu_206_p_ce : STD_LOGIC;
    signal grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_fu_202_ce : STD_LOGIC;
    signal grp_fu_206_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component hls_snn_izikevich_snn_get_synaptic_conductances_Pipeline_input_synapses_cache IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11 : OUT STD_LOGIC_VECTOR (31 downto 0);
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11_ap_vld : OUT STD_LOGIC;
        synapse_s_mem_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        synapse_s_mem_ce0 : OUT STD_LOGIC;
        synapse_s_mem_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9 : OUT STD_LOGIC_VECTOR (31 downto 0);
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9_ap_vld : OUT STD_LOGIC;
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8 : OUT STD_LOGIC_VECTOR (31 downto 0);
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8_ap_vld : OUT STD_LOGIC;
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7 : OUT STD_LOGIC_VECTOR (31 downto 0);
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7_ap_vld : OUT STD_LOGIC;
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6 : OUT STD_LOGIC_VECTOR (31 downto 0);
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6_ap_vld : OUT STD_LOGIC;
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10 : OUT STD_LOGIC_VECTOR (31 downto 0);
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10_ap_vld : OUT STD_LOGIC );
    end component;


    component hls_snn_izikevich_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        neuron_type_mem_0_load : IN STD_LOGIC_VECTOR (5 downto 0);
        neuron_type_mem_1_load : IN STD_LOGIC_VECTOR (5 downto 0);
        input_stream0_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
        input_stream0_TVALID : IN STD_LOGIC;
        input_stream0_TREADY : OUT STD_LOGIC;
        input_stream0_TKEEP : IN STD_LOGIC_VECTOR (7 downto 0);
        input_stream0_TSTRB : IN STD_LOGIC_VECTOR (7 downto 0);
        input_stream0_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        input_stream1_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
        input_stream1_TVALID : IN STD_LOGIC;
        input_stream1_TREADY : OUT STD_LOGIC;
        input_stream1_TKEEP : IN STD_LOGIC_VECTOR (7 downto 0);
        input_stream1_TSTRB : IN STD_LOGIC_VECTOR (7 downto 0);
        input_stream1_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        input_stream2_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
        input_stream2_TVALID : IN STD_LOGIC;
        input_stream2_TREADY : OUT STD_LOGIC;
        input_stream2_TKEEP : IN STD_LOGIC_VECTOR (7 downto 0);
        input_stream2_TSTRB : IN STD_LOGIC_VECTOR (7 downto 0);
        input_stream2_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        input_stream3_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
        input_stream3_TVALID : IN STD_LOGIC;
        input_stream3_TREADY : OUT STD_LOGIC;
        input_stream3_TKEEP : IN STD_LOGIC_VECTOR (7 downto 0);
        input_stream3_TSTRB : IN STD_LOGIC_VECTOR (7 downto 0);
        input_stream3_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        u_mem_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        u_mem_ce0 : OUT STD_LOGIC;
        u_mem_we0 : OUT STD_LOGIC;
        u_mem_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        u_mem_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        u_mem_ce1 : OUT STD_LOGIC;
        u_mem_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        firings_mem_0_i : IN STD_LOGIC_VECTOR (63 downto 0);
        firings_mem_0_o : OUT STD_LOGIC_VECTOR (63 downto 0);
        firings_mem_0_o_ap_vld : OUT STD_LOGIC;
        v_mem_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        v_mem_ce0 : OUT STD_LOGIC;
        v_mem_we0 : OUT STD_LOGIC;
        v_mem_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v_mem_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11_i : IN STD_LOGIC_VECTOR (31 downto 0);
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11_o : OUT STD_LOGIC_VECTOR (31 downto 0);
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11_o_ap_vld : OUT STD_LOGIC;
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9_i : IN STD_LOGIC_VECTOR (31 downto 0);
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9_o : OUT STD_LOGIC_VECTOR (31 downto 0);
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9_o_ap_vld : OUT STD_LOGIC;
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8_i : IN STD_LOGIC_VECTOR (31 downto 0);
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8_o : OUT STD_LOGIC_VECTOR (31 downto 0);
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8_o_ap_vld : OUT STD_LOGIC;
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7_i : IN STD_LOGIC_VECTOR (31 downto 0);
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7_o : OUT STD_LOGIC_VECTOR (31 downto 0);
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7_o_ap_vld : OUT STD_LOGIC;
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6_i : IN STD_LOGIC_VECTOR (31 downto 0);
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6_o : OUT STD_LOGIC_VECTOR (31 downto 0);
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6_o_ap_vld : OUT STD_LOGIC;
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10_i : IN STD_LOGIC_VECTOR (31 downto 0);
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10_o : OUT STD_LOGIC_VECTOR (31 downto 0);
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10_o_ap_vld : OUT STD_LOGIC;
        synapse_s_mem_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        synapse_s_mem_ce0 : OUT STD_LOGIC;
        synapse_s_mem_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_202_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_202_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_202_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
        grp_fu_202_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_202_p_ce : OUT STD_LOGIC;
        grp_fu_206_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_206_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_206_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_206_p_ce : OUT STD_LOGIC );
    end component;


    component hls_snn_izikevich_faddfsub_32ns_32ns_32_2_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        opcode : IN STD_LOGIC_VECTOR (1 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component hls_snn_izikevich_fmul_32ns_32ns_32_2_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98 : component hls_snn_izikevich_snn_get_synaptic_conductances_Pipeline_input_synapses_cache
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_ap_start,
        ap_done => grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_ap_done,
        ap_idle => grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_ap_idle,
        ap_ready => grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_ap_ready,
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11 => grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11,
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11_ap_vld => grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11_ap_vld,
        synapse_s_mem_address0 => grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_synapse_s_mem_address0,
        synapse_s_mem_ce0 => grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_synapse_s_mem_ce0,
        synapse_s_mem_q0 => synapse_s_mem_q0,
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9 => grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9,
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9_ap_vld => grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9_ap_vld,
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8 => grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8,
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8_ap_vld => grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8_ap_vld,
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7 => grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7,
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7_ap_vld => grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7_ap_vld,
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6 => grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6,
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6_ap_vld => grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6_ap_vld,
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10 => grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10,
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10_ap_vld => grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10_ap_vld);

    grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116 : component hls_snn_izikevich_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_ap_start,
        ap_done => grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_ap_done,
        ap_idle => grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_ap_idle,
        ap_ready => grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_ap_ready,
        neuron_type_mem_0_load => neuron_type_mem_0,
        neuron_type_mem_1_load => neuron_type_mem_1,
        input_stream0_TDATA => input_stream0_TDATA,
        input_stream0_TVALID => input_stream0_TVALID,
        input_stream0_TREADY => grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_input_stream0_TREADY,
        input_stream0_TKEEP => input_stream0_TKEEP,
        input_stream0_TSTRB => input_stream0_TSTRB,
        input_stream0_TLAST => input_stream0_TLAST,
        input_stream1_TDATA => input_stream1_TDATA,
        input_stream1_TVALID => input_stream1_TVALID,
        input_stream1_TREADY => grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_input_stream1_TREADY,
        input_stream1_TKEEP => input_stream1_TKEEP,
        input_stream1_TSTRB => input_stream1_TSTRB,
        input_stream1_TLAST => input_stream1_TLAST,
        input_stream2_TDATA => input_stream2_TDATA,
        input_stream2_TVALID => input_stream2_TVALID,
        input_stream2_TREADY => grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_input_stream2_TREADY,
        input_stream2_TKEEP => input_stream2_TKEEP,
        input_stream2_TSTRB => input_stream2_TSTRB,
        input_stream2_TLAST => input_stream2_TLAST,
        input_stream3_TDATA => input_stream3_TDATA,
        input_stream3_TVALID => input_stream3_TVALID,
        input_stream3_TREADY => grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_input_stream3_TREADY,
        input_stream3_TKEEP => input_stream3_TKEEP,
        input_stream3_TSTRB => input_stream3_TSTRB,
        input_stream3_TLAST => input_stream3_TLAST,
        u_mem_address0 => grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_u_mem_address0,
        u_mem_ce0 => grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_u_mem_ce0,
        u_mem_we0 => grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_u_mem_we0,
        u_mem_d0 => grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_u_mem_d0,
        u_mem_address1 => grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_u_mem_address1,
        u_mem_ce1 => grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_u_mem_ce1,
        u_mem_q1 => u_mem_q1,
        firings_mem_0_i => firings_mem_0_i,
        firings_mem_0_o => grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_firings_mem_0_o,
        firings_mem_0_o_ap_vld => grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_firings_mem_0_o_ap_vld,
        v_mem_address0 => grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_v_mem_address0,
        v_mem_ce0 => grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_v_mem_ce0,
        v_mem_we0 => grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_v_mem_we0,
        v_mem_d0 => grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_v_mem_d0,
        v_mem_q0 => v_mem_q0,
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11_i => snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11,
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11_o => grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11_o,
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11_o_ap_vld => grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11_o_ap_vld,
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9_i => snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9,
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9_o => grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9_o,
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9_o_ap_vld => grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9_o_ap_vld,
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8_i => snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8,
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8_o => grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8_o,
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8_o_ap_vld => grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8_o_ap_vld,
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7_i => snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7,
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7_o => grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7_o,
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7_o_ap_vld => grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7_o_ap_vld,
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6_i => snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6,
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6_o => grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6_o,
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6_o_ap_vld => grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6_o_ap_vld,
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10_i => snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10,
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10_o => grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10_o,
        snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10_o_ap_vld => grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10_o_ap_vld,
        synapse_s_mem_address0 => grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_synapse_s_mem_address0,
        synapse_s_mem_ce0 => grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_synapse_s_mem_ce0,
        synapse_s_mem_q0 => synapse_s_mem_q0,
        grp_fu_202_p_din0 => grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_grp_fu_202_p_din0,
        grp_fu_202_p_din1 => grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_grp_fu_202_p_din1,
        grp_fu_202_p_opcode => grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_grp_fu_202_p_opcode,
        grp_fu_202_p_dout0 => grp_fu_465_p_dout0,
        grp_fu_202_p_ce => grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_grp_fu_202_p_ce,
        grp_fu_206_p_din0 => grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_grp_fu_206_p_din0,
        grp_fu_206_p_din1 => grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_grp_fu_206_p_din1,
        grp_fu_206_p_dout0 => grp_fu_469_p_dout0,
        grp_fu_206_p_ce => grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_grp_fu_206_p_ce);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_ap_ready = ap_const_logic_1)) then 
                    grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_ap_ready = ap_const_logic_1)) then 
                    grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10_o_ap_vld = ap_const_logic_1))) then 
                snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10 <= grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10_o;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10_ap_vld = ap_const_logic_1))) then 
                snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10 <= grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_10;
            end if; 
        end if;
    end process;

    snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11_o_ap_vld = ap_const_logic_1))) then 
                snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11 <= grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11_o;
            elsif (((grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11 <= grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_11;
            end if; 
        end if;
    end process;

    snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6_o_ap_vld = ap_const_logic_1))) then 
                snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6 <= grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6_o;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6_ap_vld = ap_const_logic_1))) then 
                snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6 <= grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_6;
            end if; 
        end if;
    end process;

    snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7_o_ap_vld = ap_const_logic_1))) then 
                snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7 <= grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7_o;
            elsif (((grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7 <= grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_7;
            end if; 
        end if;
    end process;

    snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8_o_ap_vld = ap_const_logic_1))) then 
                snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8 <= grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8_o;
            elsif (((grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8 <= grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_8;
            end if; 
        end if;
    end process;

    snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9_o_ap_vld = ap_const_logic_1))) then 
                snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9 <= grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9_o;
            elsif (((grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9 <= grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_snn_get_synaptic_conductances_ap_uint_const_6_float_const_6_float_flo_9;
            end if; 
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_ap_done, grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_ap_done)
    begin
        if ((grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_ap_done)
    begin
        if ((grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_ap_done, ap_CS_fsm_state4)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_ap_done = ap_const_logic_1)) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_ap_done, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_ap_done = ap_const_logic_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    firings_mem_0_o_assign_proc : process(firings_mem_0_i, grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_firings_mem_0_o, grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_firings_mem_0_o_ap_vld, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_firings_mem_0_o_ap_vld = ap_const_logic_1))) then 
            firings_mem_0_o <= grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_firings_mem_0_o;
        else 
            firings_mem_0_o <= firings_mem_0_i;
        end if; 
    end process;

    firings_mem_0_o_ap_vld <= grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_firings_mem_0_o_ap_vld;

    grp_fu_202_ce_assign_proc : process(grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_grp_fu_202_p_ce, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_202_ce <= grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_grp_fu_202_p_ce;
        else 
            grp_fu_202_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_206_ce_assign_proc : process(grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_grp_fu_206_p_ce, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_206_ce <= grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_grp_fu_206_p_ce;
        else 
            grp_fu_206_ce <= ap_const_logic_1;
        end if; 
    end process;

    grp_fu_465_p_ce <= grp_fu_202_ce;
    grp_fu_465_p_din0 <= grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_grp_fu_202_p_din0;
    grp_fu_465_p_din1 <= grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_grp_fu_202_p_din1;
    grp_fu_465_p_opcode <= grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_grp_fu_202_p_opcode;
    grp_fu_469_p_ce <= grp_fu_206_ce;
    grp_fu_469_p_din0 <= grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_grp_fu_206_p_din0;
    grp_fu_469_p_din1 <= grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_grp_fu_206_p_din1;
    grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_ap_start <= grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_ap_start_reg;
    grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_ap_start <= grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_ap_start_reg;

    input_stream0_TREADY_assign_proc : process(grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_input_stream0_TREADY, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            input_stream0_TREADY <= grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_input_stream0_TREADY;
        else 
            input_stream0_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    input_stream1_TREADY_assign_proc : process(grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_input_stream1_TREADY, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            input_stream1_TREADY <= grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_input_stream1_TREADY;
        else 
            input_stream1_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    input_stream2_TREADY_assign_proc : process(grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_input_stream2_TREADY, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            input_stream2_TREADY <= grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_input_stream2_TREADY;
        else 
            input_stream2_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    input_stream3_TREADY_assign_proc : process(grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_input_stream3_TREADY, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            input_stream3_TREADY <= grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_input_stream3_TREADY;
        else 
            input_stream3_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    synapse_s_mem_address0_assign_proc : process(grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_synapse_s_mem_address0, grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_synapse_s_mem_address0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            synapse_s_mem_address0 <= grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_synapse_s_mem_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            synapse_s_mem_address0 <= grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_synapse_s_mem_address0;
        else 
            synapse_s_mem_address0 <= "XXXX";
        end if; 
    end process;


    synapse_s_mem_ce0_assign_proc : process(grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_synapse_s_mem_ce0, grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_synapse_s_mem_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            synapse_s_mem_ce0 <= grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_synapse_s_mem_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            synapse_s_mem_ce0 <= grp_snn_get_synaptic_conductances_Pipeline_input_synapses_cache_fu_98_synapse_s_mem_ce0;
        else 
            synapse_s_mem_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    u_mem_address0 <= grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_u_mem_address0;
    u_mem_address1 <= grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_u_mem_address1;
    u_mem_ce0 <= grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_u_mem_ce0;
    u_mem_ce1 <= grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_u_mem_ce1;
    u_mem_d0 <= grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_u_mem_d0;
    u_mem_we0 <= grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_u_mem_we0;
    v_mem_address0 <= grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_v_mem_address0;
    v_mem_ce0 <= grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_v_mem_ce0;
    v_mem_d0 <= grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_v_mem_d0;
    v_mem_we0 <= grp_snn_get_synaptic_conductances_Pipeline_synaptic_conductances_VITIS_LOOP_154_1_fu_116_v_mem_we0;
end behav;
